<?php
/**
 * Proof — the two daily jobs of the worker: (1) the 14-day Reservations covers fill that slice 5 deferred (K7 through the stubbed kernel, degrading to a logged word, once a day, never over a typed cell), and
 * (2) the manager's certification warning that slice 4 deferred (read from mcp_certifications_due as a manager; once per card and state and manager; never to the person, never for a missing or unverified card).
 */
require __DIR__ . '/lib.php';
$W = reset6();
$tzA = new DateTimeZone('America/Chicago');
$today = (new DateTimeImmutable('now', $tzA))->format('Y-m-d');
$d = fn (int $n): string => (new DateTimeImmutable($today, $tzA))->modify(sprintf('%+d days', $n))->format('Y-m-d');
$lunch = dpid(102, 'lunch'); $dinner = dpid(102, 'dinner');
$asked = fn (): array => kreads();
admin_sql("DELETE FROM forecast_covers; DELETE FROM activity_log WHERE action = 'notification.daily'");
echo "1. The daily fill — no connection yet\n";
kread(['mode' => 'no_connection']); @unlink(need('FAKE_KERNEL_STATE') . '.reads');
$since = last_activity_id();
$r = worker('--only=forecast');
$reads = kreads();
ok(($r['forecast']['sites'] ?? 0) === 2 && ($r['forecast']['refused'] ?? 0) === 2 && ($r['forecast']['written'] ?? -1) === 0 && count($reads) === 2, 'both restaurants asked once; both refused; nothing written (' . json_encode($r) . ')');
$b = $reads[0]['body'];
ok($b['provider'] === 'reservations' && $b['tool'] === 'covers_by_service' && $b['arguments'] === ['from' => $today, 'to' => $d(13)] && $b['location_id'] === loc_of(102) || $b['location_id'] === loc_of(101), 'each K7 call asks for today through the 13th day after, at the restaurant\'s own location: ' . json_encode($b));
$lg = q("SELECT scope_id, source, actor_member_id, after FROM activity_log WHERE action = 'forecast.fill' AND id > :s ORDER BY id", ['s' => $since]);
ok(count($lg) === 2 && $lg[0]['source'] === 'cron' && $lg[0]['actor_member_id'] === null && json_decode($lg[0]['after'], true)['refusal'] === 'no_connection' && json_decode($lg[0]['after'], true)['via'] === 'timer', 'each attempt is a forecast.fill row: source cron, the site, refusal no_connection, via timer');
worker('--only=forecast');
ok(count(kreads()) === 2, 'the same day, the next passes do not ask again (the daily marker)');
ok((int) one("SELECT count(*) FROM activity_log WHERE action = 'notification.daily' AND after->>'step' = 'forecast_fill'") === 2, 'the marker is one notification.daily row per restaurant');
echo "2. The connection approved: the next 14 days, week by week\n";
admin_sql("UPDATE activity_log SET occurred_at = occurred_at - interval '1 day' WHERE action = 'notification.daily'");
put_cell(102, $d(2), $dinner, 77, 'manual');
$rows = [['date' => $d(2), 'service' => 'Lunch', 'reservations' => 5, 'covers' => 21], ['date' => $d(2), 'service' => 'Dinner', 'reservations' => 9, 'covers' => 40], ['date' => $d(9), 'service' => 'Dinner', 'reservations' => 7, 'covers' => 33],
         ['date' => $d(13), 'service' => 'Lunch', 'reservations' => 3, 'covers' => 12], ['date' => $d(13), 'service' => 'Brunch', 'reservations' => 3, 'covers' => 9], ['date' => $d(14), 'service' => 'Dinner', 'reservations' => 2, 'covers' => 8], ['date' => $d(20), 'service' => 'Dinner', 'reservations' => 2, 'covers' => 8]];
kread(['mode' => 'ok', 'rows' => $rows, 'locations' => [loc_of(102)]]);
@unlink(need('FAKE_KERNEL_STATE') . '.reads');
$since = last_activity_id();
$r = worker('--only=forecast');
ok(($r['forecast']['written'] ?? 0) === 3 && ($r['forecast']['refused'] ?? 0) === 1, 'Airport filled 3 cells; Downtown, which Reservations does not serve, was refused (' . json_encode($r['forecast'] ?? $r) . ')');
$c = fn (string $date, int $dp) => cell(102, $date, $dp);
ok($c($d(2), $lunch)['expected_covers'] == 21 && $c($d(2), $lunch)['source'] === 'reservations' && $c($d(2), $lunch)['updated_by'] === null && $c($d(9), $dinner)['expected_covers'] == 33 && $c($d(13), $lunch)['expected_covers'] == 12, 'the booked covers landed as source reservations, not attributed to any person');
ok($c($d(2), $dinner)['expected_covers'] == 77 && $c($d(2), $dinner)['source'] === 'manual', 'a typed cell (77) was left alone');
ok($c($d(14), $dinner) === null && $c($d(20), $dinner) === null && n_cells(102) === 4, 'day 14 and day 20 (beyond the window) were not written; the unmapped service (Brunch) was not either');
$lg = q("SELECT scope_id, after FROM activity_log WHERE action = 'forecast.fill' AND scope_id = 102 AND id > :s ORDER BY id", ['s' => $since]);
$sum = array_sum(array_map(fn ($x) => json_decode($x['after'], true)['written'], $lg));
ok(count($lg) >= 2 && $sum === 3 && count(array_filter($lg, fn ($x) => json_decode($x['after'], true)['unmapped'] !== [])) >= 1, 'one forecast.fill row per week touched (' . count($lg) . '), 3 cells in all, the unmapped service listed');
ok(count(kreads()) === 2 && !str_contains(json_encode($lg), 'reservations":'), 'the kernel was asked once per restaurant and its answer is not kept in the log');
worker('--only=forecast');
ok(count(kreads()) === 2 && n_cells(102) === 4, 'a second pass the same day asks nothing and changes nothing');
echo "3. An unreachable provider is tried again\n";
admin_sql("UPDATE activity_log SET occurred_at = occurred_at - interval '1 day' WHERE action = 'notification.daily'");
kread(['mode' => 'provider_failed']); @unlink(need('FAKE_KERNEL_STATE') . '.reads');
worker('--only=forecast'); worker('--only=forecast');
ok(count(kreads()) === 4, 'provider_failed is not marked done: the next pass asks again (4 asks for 2 restaurants over 2 passes)');
kread(['mode' => 'ok', 'rows' => [['date' => $d(3), 'service' => 'Dinner', 'reservations' => 1, 'covers' => 50]], 'locations' => [loc_of(102), loc_of(101)]]);
$r = worker('--only=forecast');
ok(($r['forecast']['written'] ?? 0) >= 1 && cell(102, $d(3), $dinner)['expected_covers'] == 50, 'and when it answers, the forecast fills');
worker('--only=forecast');
ok(count(kreads()) === 6, 'then it rests for the day');
echo "4. Certification warnings for managers\n";
as_planner(); as_setter();
admin_sql("DELETE FROM notification_outbox; DELETE FROM certifications;");
$kind = (int) one("SELECT id FROM certification_kinds WHERE scope_id = 102 AND key = 'food_handler'");
$kindD = (int) one("SELECT id FROM certification_kinds WHERE scope_id = 101 AND key = 'food_handler'");
$card = fn (int $m, int $k, string $exp, string $verified = 'now()') => (int) one("INSERT INTO certifications (member_id, kind_id, expires_on, verified_at, verified_by) VALUES ($m, $k, :e, " . ($verified === 'now()' ? 'now()' : 'NULL') . ", 33) RETURNING id", ['e' => $exp]);
$ana = $card(30, $kind, $d(10)); $lee = $card(31, $kind, $d(-5)); $priya = $card(26, $kind, $d(90)); $dana = $card(32, $kind, $d(200), 'null'); $joe = $card(34, $kindD, $d(3));
$managers = staff_with('schedule.build', 102);
$mgrD = staff_with('schedule.build', 101);
ok(in_array(33, $managers, true) && !in_array(27, $managers, true) && in_array(27, $mgrD, true) && !in_array(33, $mgrD, true) && in_array(1, $managers, true) && in_array(1, $mgrD, true), 'Airport\'s managers (' . implode(',', $managers) . ') and Downtown\'s (' . implode(',', $mgrD) . ') differ; the owner is both');
$r = worker('--only=certs');
$rows = q("SELECT * FROM notification_outbox WHERE dedupe_key LIKE 'cert:%' ORDER BY id");
$by = fn (int $card, string $state) => array_values(array_filter($rows, fn ($x) => str_starts_with($x['dedupe_key'], "cert:$card:$state:")));
$told = fn (array $rs) => array_values(array_unique(array_map(fn ($x) => (int) $x['member_id'], $rs)));
sort($managers); sort($mgrD);
$t = $told($by($ana, 'due')); sort($t);
ok($t === $managers && count($by($ana, 'due')) === count($managers) * 2, 'Ana\'s card (10 days left) warns each Airport manager, once per channel');
$t = $told($by($lee, 'expired')); sort($t);
ok($t === $managers, 'Lee\'s expired card warns them too');
ok($by($priya, 'due') === [] && $by($priya, 'expired') === [] && $by($dana, 'due') === [], 'Priya\'s card (90 days) and Dana\'s unverified one (200 days — to verify, not a warning) do not');
$t = $told($by($joe, 'due')); sort($t);
ok($t === $mgrD && !in_array(33, $t, true), 'Joe\'s card at Downtown warns Downtown\'s manager and not Airport\'s');
ok(array_diff($told($rows), array_merge($managers, $mgrD)) === [] && !array_intersect($told($rows), [26, 30, 31, 32, 34]), 'nobody but managers is told — never the person whose card it is');
$b = $by($ana, 'due')[0]['body'];
ok(str_contains($b, "SMOKE Ana's Food handler card runs out on") && str_contains($b, '10 days left') && str_contains($b, '(SMOKE Airport)') && str_contains($b, '/certifications/?site=102'), 'the words: ' . $b);
ok(str_contains($by($lee, 'expired')[0]['body'], 'ran out on') && $by($lee, 'expired')[0]['kind'] === 'reminder' && $by($lee, 'expired')[0]['reference'] === "certification:$lee", 'an expired one says "ran out on", kind reminder, referenced to the card');
$leak = []; foreach ($rows as $x) { $leak = array_merge($leak, notice_leaks($x['subject'] . $x['body'], (int) $x['member_id'])); }
ok($leak === [], 'no wage, phone or email in any of them');
$n = (int) one('SELECT count(*) FROM notification_outbox');
worker('--only=certs'); worker('--only=certs');
ok((int) one('SELECT count(*) FROM notification_outbox') === $n, 'more passes warn nobody twice');
admin_sql("UPDATE certifications SET expires_on = current_date - 1 WHERE id = $ana");
worker('--only=certs');
ok(count($by2 = q("SELECT 1 FROM notification_outbox WHERE dedupe_key LIKE 'cert:$ana:expired:%'")) === count($managers) * 2, 'when Ana\'s card runs out she is warned about afresh: the expired notice');
$renew = $card(30, $kind, $d(200));
$n = (int) one('SELECT count(*) FROM notification_outbox');
worker('--only=certs');
ok((int) one('SELECT count(*) FROM notification_outbox') === $n, 'a renewal card (200 days) warns nobody');
act(as_member(33), '/settings/prefs.php', ['kinds' => ['schedule_published']]);
$card(35, $kind, $d(2));
admin_sql("INSERT INTO member_site_roles (member_id, scope_id, role_key, roles, capability) VALUES (35, 102, 'planner', '{planner}', 'write') ON CONFLICT DO NOTHING");
$mm = $card(37, $kind, $d(1));
worker('--only=certs');
$forMara = q("SELECT 1 FROM notification_outbox WHERE dedupe_key LIKE 'cert:$mm:due:33:%'");
ok($forMara === [] && q("SELECT 1 FROM notification_outbox WHERE dedupe_key LIKE 'cert:$mm:due:1:%'") !== [], 'Mara turned reminders off: her copy is not queued; the owner\'s is');
admin_sql("DELETE FROM certifications; DELETE FROM notification_outbox; DELETE FROM forecast_covers; DELETE FROM member_site_roles WHERE member_id = 35 AND scope_id = 102");
kread(['mode' => 'no_connection']);
finish();
