<?php
/** Proof — time off (spec "Proof": Time off): blackout and not-offered refusals, approval draws the balance and writes one ledger row, cancel gives it back, "Not enough" at approval, allow_negative, "Also open those shifts", notices, cancel and decide rules, who is off. */
require __DIR__ . '/lib.php';
$W = reset3();
$priya = as_member(26); $ana = as_member(30); $lee = as_member(31); $mara = as_member(33); $owner = as_member(1, 102); $marco = as_member(27, 101);
$srv = srv();
$vac = typ(102, 'vacation'); $sick = typ(102, 'sick'); $unpaid = typ(102, 'unpaid'); $dvac = typ(101, 'vacation');
$w = wk(70);
$day = fn (int $i): string => dayn($w, $i);

echo "1. A blackout date refuses the request, with the reason\n";
[$c, $b] = act($owner, '/time-off/blackout/save.php', ['site' => 102, 'on_date' => $day(2), 'reason' => "Valentine's Day"]);
$bo = (int) ($b['record_id'] ?? 0);
ok($c === 200 && $bo > 0 && preg_match('~#blackout-' . $bo . '$~', (string) $b['location']), 'blackout_save (the owner): 200, record_id, the location ends in the id');
ok((int) one("SELECT count(*) FROM activity_log WHERE action = 'blackout.save' AND entity_id = :i AND scope_id = 102", ['i' => $bo]) === 1, 'blackout.save is logged with the site');
$n0 = (int) one('SELECT count(*) FROM time_off_requests');
[$c, $b] = req_off($priya, $vac, $day(1), $day(3));
ok($c === 422 && msg($b) === "No time off on that date: Valentine's Day." && (int) one('SELECT count(*) FROM time_off_requests') === $n0, 'a request that touches it: 422 "' . msg($b) . '", nothing stored');
[$c, $b] = req_off($priya, $vac, $day(2), $day(2));
ok($c === 422 && str_contains(msg($b), "Valentine's Day"), 'the day itself: 422');
[$c, $b] = req_off($priya, $vac, $day(3), $day(4));
ok($c === 200, 'the day after is fine (200)');
$firstAfter = (int) $b['record_id'];
$p = html_entity_decode(page($priya, "/time-off/new?site=102&from={$day(1)}&to={$day(3)}&preview=1")['body']);
ok(str_contains($p, "No time off on that date: Valentine's Day."), 'the form\'s preview says the same before she asks');
[$c, $b] = act($mara, '/time-off/blackout/save.php', ['site' => 102, 'on_date' => $day(2), 'reason' => 'SMOKE again']);
ok($c === 403, 'a manager without settings.manage cannot black out a date: 403');
[$c, $b] = act($owner, '/time-off/blackout/save.php', ['site' => 102, 'on_date' => $day(2), 'reason' => 'SMOKE again']);
ok($c === 422 && msg($b) === 'That date is already blacked out.', 'the same date twice: 422 "' . msg($b) . '"');
[$c, $b] = act($owner, '/time-off/blackout/save.php', ['site' => 102, 'on_date' => $day(2)]);
ok($c === 422, 'a blackout without a reason: 422 (' . msg($b) . ')');
act($priya, '/time-off/cancel.php', ['request' => $firstAfter]);

echo "2. A kind the restaurant does not offer\n";
admin_sql("UPDATE time_off_types SET archived_at = now() WHERE id = $sick");
[$c, $b] = req_off($priya, $sick, $day(4), $day(4));
ok($c === 422 && msg($b) === 'That kind of time off is not offered here.', 'an archived kind: 422 "' . msg($b) . '"');
admin_sql("UPDATE time_off_types SET archived_at = NULL WHERE id = $sick");
[$c, $b] = req_off($priya, $dvac, $day(4), $day(4));
ok($c === 404 && msg($b) === 'That kind of time off is not offered here.', 'Downtown\'s kind, which Priya does not hold: 404, the same sentence');
[$c, $b] = req_off($marco, $dvac, $day(4), $day(4), ['site' => 102]);
ok($c === 422 && msg($b) === 'That kind of time off belongs to a different restaurant.', 'a person who holds both, naming the other restaurant: 422 "' . msg($b) . '"');
[$c, $b] = act($priya, '/time-off/request.php', ['from' => $day(4), 'to' => $day(4)]);
ok($c === 422 && msg($b) === 'Choose the kind of time off.', 'no kind: 422 "' . msg($b) . '"');

echo "3. Approval draws the balance down; cancelling gives it back\n";
grant(26, $vac, 16);
$ob = last_outbox_id();
[$c, $b] = req_off($priya, $vac, $day(4), $day(4), ['note' => 'SMOKE dentist']);
$r1 = (int) ($b['record_id'] ?? 0);
ok($c === 200 && $r1 > 0 && $b['location'] === "/time-off/$r1" && (float) $b['hours'] === 8.0 && status_off($r1) === 'pending', 'time_off_request: 200, the location is /time-off/{id}, hours counted by the database (8), pending');
$r = q('SELECT hours, note, decided_by FROM time_off_requests WHERE id = :i', ['i' => $r1])[0];
ok((float) $r['hours'] === 8.0 && $r['note'] === 'SMOKE dentist' && $r['decided_by'] === null, 'stored with the person\'s note');
ok((int) one("SELECT count(*) FROM activity_log WHERE action = 'timeoff.request' AND entity_id = :i AND scope_id = 102 AND source = 'web'", ['i' => $r1]) === 1, 'timeoff.request logged with the site, source web');
$told = told_ref("time_off:$r1");
ok(in_array(33, $told, true) && in_array(1, $told, true) && !in_array(26, $told, true) && (int) one("SELECT count(*) FROM notification_outbox WHERE reference = :r AND kind = 'request_decided' AND subject = 'Time off to approve' AND channel = 'email'", ['r' => "time_off:$r1"]) >= 2, 'the approvers are told ("Time off to approve"), not the person: ' . json_encode($told));
$page = html_entity_decode(page($priya, "/time-off/$r1")['body']);
ok(str_contains($page, 'Balance 16 h — this uses 8 h, leaving 8 h.') && str_contains($page, 'Waiting for a manager'), 'her request page: "Balance 16 h — this uses 8 h, leaving 8 h." and waiting');
ok(bal(26, $vac) === 16.0 && count(ledger_rows(26, $vac)) === 1, 'nothing has moved yet: balance 16, one ledger row (the grant)');
$since = last_activity_id(); $ob = last_outbox_id();
[$c, $b] = act($mara, '/time-off/approve.php', ['request' => $r1, 'note' => 'SMOKE enjoy']);
ok($c === 200 && ($b['status'] ?? '') === 'approved' && (float) $b['balance_hours'] === 8.0, 'time_off_approve: 200, balance 8');
$led = ledger_rows(26, $vac);
ok(bal(26, $vac) === 8.0 && count($led) === 2 && $led[1]['reason'] === 'request_approved' && (float) $led[1]['delta_hours'] === -8.0 && (int) $led[1]['request_id'] === $r1, 'balance 8, exactly ONE new ledger row: request_approved −8 for that request');
$lg = q("SELECT after, scope_id FROM activity_log WHERE action = 'timeoff.approve' AND entity_id = :i AND id > :s", ['i' => $r1, 's' => $since]);
$after = json_decode($lg[0]['after'] ?? '{}', true);
ok(count($lg) === 1 && (int) $lg[0]['scope_id'] === 102 && $after['hours'] == 8 && $after['balance_hours'] == 8 && $after['shifts_opened'] === [], 'timeoff.approve logged with the site: hours, balance_hours, shifts_opened');
ok(!str_contains($lg[0]['after'], 'wage') && !str_contains($lg[0]['after'], 'rate') && !str_contains($lg[0]['after'], 'cost'), 'the log row carries hours, never pay');
$mine = array_filter(outbox_ref("time_off:$r1"), fn ($x) => (int) $x['member_id'] === 26 && $x['id'] > $ob && str_contains($x['body'] . $x['subject'], 'approved'));
ok(count($mine) >= 2, 'Priya is told (email and text) — "Your time off was approved"');
[$c, $b] = act($mara, '/time-off/approve.php', ['request' => $r1]);
ok($c === 422 && msg($b) === 'This request was already approved.', 'approving it again: 422 "' . msg($b) . '"');
$since = last_activity_id(); $ob = last_outbox_id();
[$c, $b] = act($priya, '/time-off/cancel.php', ['request' => $r1]);
$led = ledger_rows(26, $vac);
ok($c === 200 && status_off($r1) === 'cancelled' && bal(26, $vac) === 16.0 && count($led) === 3 && $led[2]['reason'] === 'request_cancelled' && (float) $led[2]['delta_hours'] === 8.0, 'Priya cancels: 200, 16 h back, three ledger rows (grant, approved, cancelled)');
$lg = q("SELECT after FROM activity_log WHERE action = 'timeoff.cancel' AND entity_id = :i AND scope_id = 102 AND id > :s", ['i' => $r1, 's' => $since]);
ok(count($lg) === 1 && json_decode($lg[0]['after'], true)['hours_returned'] == 8, 'timeoff.cancel logged with the site and hours_returned 8');
ok(count(array_filter(outbox_ref("time_off:$r1"), fn ($x) => $x['id'] > $ob && in_array((int) $x['member_id'], [33, 1], true) && str_contains($x['subject'] ?? '', 'cancelled'))) >= 2, 'the approvers are told an approved request was cancelled');
[$c, $b] = act($priya, '/time-off/cancel.php', ['request' => $r1]);
ok($c === 422 && msg($b) === 'This request was already cancelled.', 'cancelling twice: 422 "' . msg($b) . '"');
ok((float) one('SELECT sum(delta_hours) FROM time_off_ledger WHERE member_id = 26 AND type_id = :t', ['t' => $vac]) === bal(26, $vac), 'the balance is the sum of its ledger');

echo "4. 24 h with 16 left: asked, refused at approval\n";
[$c, $b] = req_off($priya, $vac, $day(3), $day(5));
$r2 = (int) ($b['record_id'] ?? 0);
ok($c === 200 && (float) $b['hours'] === 24.0 && $b['status'] === 'pending', 'three days count 24 h and may be ASKED (200)');
$page = html_entity_decode(page($mara, '/approvals')['body']);
ok(str_contains($page, 'It cannot be approved: not enough is left.'), 'the approver\'s card says so before she tries');
$since = last_activity_id(); $n = count(ledger_rows(26, $vac));
[$c, $b] = act($mara, '/time-off/approve.php', ['request' => $r2]);
ok($c === 422 && str_starts_with(msg($b), 'Not enough vacation / pto left: this needs 24'), 'approval: 422 "' . msg($b) . '"');
ok(status_off($r2) === 'pending' && bal(26, $vac) === 16.0 && count(ledger_rows(26, $vac)) === $n && (int) one("SELECT count(*) FROM activity_log WHERE id > :s AND action = 'timeoff.approve'", ['s' => $since]) === 0, 'still pending, balance 16, no ledger row, nothing logged as approved');
[$c, $b] = act($mara, '/time-off/decline.php', ['request' => $r2, 'note' => 'SMOKE too long']);
ok($c === 200 && status_off($r2) === 'declined' && bal(26, $vac) === 16.0, 'a decline needs no balance: 200 declined, 16 h untouched');
ok(count(array_filter(outbox_ref("time_off:$r2"), fn ($x) => (int) $x['member_id'] === 26 && str_contains($x['body'], 'declined') && str_contains($x['body'], 'too long'))) >= 1, 'Priya is told it was declined, with the note');
[$c, $b] = act($mara, '/time-off/decline.php', ['request' => $r2]);
ok($c === 422, 'declining twice: 422 "' . msg($b) . '"');

echo "5. A kind that allows going below zero\n";
[$c, $b] = act($owner, '/time-off/types/save.php', ['site' => 102, 'name' => 'SMOKE Advance', 'paid' => 'yes', 'tracks_balance' => 'yes', 'allow_negative' => 'yes', 'sort_order' => 9]);
$adv = (int) ($b['record_id'] ?? 0);
ok($c === 200 && $adv > 0 && preg_match('~#type-' . $adv . '$~', (string) ($b['location'] ?? '')), 'time_off_type_save (the owner): 200, a new kind, the location ends in its id');
$t = q('SELECT key, paid, tracks_balance, allow_negative FROM time_off_types WHERE id = :i', ['i' => $adv])[0];
ok($t['key'] === 'smoke_advance' && $t['paid'] && $t['tracks_balance'] && $t['allow_negative'], 'its key is made from the name (smoke_advance)');
[$c, $b] = req_off($priya, $adv, $day(3), $day(5));
$r3 = (int) $b['record_id'];
[$c, $b] = act($mara, '/time-off/approve.php', ['request' => $r3]);
ok($c === 200 && bal(26, $adv) === -24.0 && (float) $b['balance_hours'] === -24.0, 'the 24 h go through: balance −24 h');
[$c, $b] = act($priya, '/time-off/cancel.php', ['request' => $r3]);
ok($c === 200 && bal(26, $adv) === 0.0, 'and cancelling puts it back to 0');
echo "   — a kind that keeps no balance moves no ledger\n";
[$c, $b] = req_off($priya, $unpaid, $day(3), $day(3));
$r4 = (int) $b['record_id'];
[$c, $b] = act($mara, '/time-off/approve.php', ['request' => $r4]);
ok($c === 200 && (int) one('SELECT count(*) FROM time_off_ledger WHERE type_id = :t', ['t' => $unpaid]) === 0 && $b['balance_hours'] === null, 'unpaid: approved, no ledger row, no balance');
act($priya, '/time-off/cancel.php', ['request' => $r4]);

echo "6. Approve + \"Also open those shifts\"\n";
$w2 = wk(71);
$dd = fn (int $i): string => dayn($w2, $i);
$wed = pub_shift(102, $srv, 26, $w2, 2);              // outside the request
$thu = pub_shift(102, $srv, 26, $w2, 3, '11:00', '15:00');
$fri = pub_shift(102, $srv, 26, $w2, 4, '17:00', '23:00');
$fri2 = pub_shift(102, $srv, 30, $w2, 4, '17:00', '23:00');    // Ana — someone else's, same day
$fri3 = pub_shift(102, $srv, 26, $w2, 4, '10:00', '11:00');    // will be cancelled
act($mara, '/shifts/cancel.php', ['shift' => $fri3, 'reason' => 'SMOKE not needed']);
$sun = fx(102, $srv, 26, wk(72), 3);                            // a DRAFT week's shift is not one of the published ones
grant(26, $vac, 0.0 + 8);                                       // 24 h on the books
[$c, $b] = req_off($priya, $vac, $dd(3), $dd(4));
$r5 = (int) $b['record_id'];
$xo = offer($priya, $fri);
ok($xo > 0 && status_of($xo) === 'open', 'Priya has put her Friday shift on the marketplace');
[$c, $d] = screen($mara, '/approvals');
$card = array_values(array_filter($d['time_off'], fn ($x) => $x['request_id'] === $r5))[0] ?? null;
$cov = array_column($card['covered_shifts'] ?? [], 'shift_id');
sort($cov);
ok($card !== null && $cov === [$thu, $fri] && !in_array($wed, $cov, true) && !in_array($fri2, $cov, true) && !in_array($fri3, $cov, true) && !in_array($sun, $cov, true), 'the approver\'s card lists exactly the covered published shifts: Thursday and Friday of Priya\'s — not Wednesday, not Ana\'s, not the cancelled one, not a draft');
ok(($card['balance']['hours'] ?? null) == 24 && ($card['balance']['after_approval'] ?? null) == 8, 'and the balance before and after: 24 h → 8 h');
$page = html_entity_decode(page($mara, '/approvals')['body']);
ok(str_contains($page, 'id="request-card-' . $r5 . '-shift-' . $thu . '"') && str_contains($page, 'id="request-card-' . $r5 . '-shift-' . $fri . '"') && str_contains($page, 'Also open those shifts'), 'the page shows the two shifts and the "Also open those shifts" box');
[$c, $d] = screen($mara, "/time-off/$r5");
ok(array_column($d['request']['covered_shifts'], 'shift_id') === [$thu, $fri], 'the request page lists them too');
// approve WITHOUT opening: the shifts stay
[$c, $b] = act($mara, '/time-off/approve.php', ['request' => $r5, 'open_shifts' => 'no']);
$sh = q('SELECT id, assignee_member_id, changed_after_publish_at FROM shifts WHERE id IN (:a, :b) ORDER BY id', ['a' => $thu, 'b' => $fri]);
ok($c === 200 && (int) $b['shifts_opened'] === 0 && (int) $sh[0]['assignee_member_id'] === 26 && (int) $sh[1]['assignee_member_id'] === 26 && (int) one("SELECT count(*) FROM activity_log WHERE action = 'shift.change' AND entity_id IN ($thu, $fri)") === 0, 'without the box the shifts stay Priya\'s and no shift.change is written');
act($priya, '/time-off/cancel.php', ['request' => $r5]);
[$c, $b] = req_off($priya, $vac, $dd(3), $dd(4));
$r6 = (int) $b['record_id'];
$since = last_activity_id(); $ob = last_outbox_id();
[$c, $b] = act($mara, '/time-off/approve.php', ['request' => $r6, 'open_shifts' => 'yes']);
ok($c === 200 && (int) $b['shifts_opened'] === 2 && status_off($r6) === 'approved', 'approve with open_shifts: 200, two shifts opened');
$sh = q('SELECT id, assignee_member_id, changed_after_publish_at, status FROM shifts WHERE id IN (:a, :b, :c, :d) ORDER BY id', ['a' => $thu, 'b' => $fri, 'c' => $wed, 'd' => $fri2]);
$by = array_column($sh, null, 'id');
ok($by[$thu]['assignee_member_id'] === null && $by[$fri]['assignee_member_id'] === null && $by[$thu]['changed_after_publish_at'] !== null && $by[$fri]['changed_after_publish_at'] !== null && $by[$thu]['status'] === 'scheduled', 'both are open now, still scheduled, and stamped as changed after publishing');
ok((int) $by[$wed]['assignee_member_id'] === 26 && (int) $by[$fri2]['assignee_member_id'] === 30, 'Wednesday and Ana\'s shift are untouched');
$rows = q("SELECT entity_id, scope_id, source, before, after FROM activity_log WHERE action = 'shift.change' AND id > :s ORDER BY entity_id", ['s' => $since]);
ok(count($rows) === 2 && array_reduce($rows, fn ($ok, $x) => $ok && (int) $x['scope_id'] === 102 && json_decode($x['after'], true)['via'] === 'time_off' && (int) json_decode($x['before'], true)['assignee_member_id'] === 26 && json_decode($x['after'], true)['request_id'] === $r6, true), 'two shift.change rows with the site, before = Priya, after.via = time_off and the request');
ok(status_of($xo) === 'cancelled', 'the trade going on Friday\'s shift was withdrawn');
$told = array_filter(outbox_ref("shift:$fri"), fn ($x) => $x['id'] > $ob && (int) $x['member_id'] === 26 && $x['kind'] === 'shift_changed');
ok(count($told) >= 2 && str_contains(reset($told)['body'], 'time off was approved'), 'the old holder is told (shift_changed, email and text): "taken off your schedule because your time off was approved"');
$lg = json_decode((string) one("SELECT after FROM activity_log WHERE action = 'timeoff.approve' AND entity_id = :i", ['i' => $r6]), true);
ok(count($lg['shifts_opened']) === 2, 'timeoff.approve records which shifts it opened');
[$c, $d] = screen($mara, "/builder?site=102&week=$w2");
$js = array_column($d['shifts'] ?? [], null, 'shift_id');
ok(isset($js[$thu], $js[$fri]) && ($js[$thu]['is_open'] ?? false) === true && ($js[$fri]['is_open'] ?? false) === true && ($js[$wed]['is_open'] ?? true) === false, 'the builder shows the gap: Thursday and Friday open, Wednesday not');
$cx = html_entity_decode(page($mara, "/coverage?site=102")['body']);
ok($c === 200, 'the coverage screen still answers (' . $c . ')');
[$c, $b] = act($mara, '/shifts/change.php', ['shift' => $thu, 'assignee' => 26]);
ok($c === 422 && str_contains(msg($b), 'On approved time off then.'), 'the rules engine knows: putting her back on Thursday is refused "' . msg($b) . '"');
[$c, $d] = screen($mara, "/time-off/$r6");
ok(($d['request']['covered_shifts'] ?? []) === [], 'the approved request no longer lists shifts (none is still hers)');
act($priya, '/time-off/cancel.php', ['request' => $r6]);

echo "7. Who may decide and cancel\n";
[$c, $b] = act($lee, '/time-off/approve.php', ['request' => $r5]);
ok($c === 403, 'a colleague (staff) approving: 403 "' . msg($b) . '"');
[$c, $b] = req_off($priya, $vac, $dd(6), $dd(6));
$r7 = (int) $b['record_id'];
[$c, $b] = act($lee, '/time-off/cancel.php', ['request' => $r7]);
ok($c === 403 && msg($b) === 'Only the person who asked, or a manager, can cancel time off.', 'a colleague cancelling Priya\'s: 403 "' . msg($b) . '"');
[$c, $b] = act($priya, '/time-off/approve.php', ['request' => $r7]);
ok($c === 403, 'Priya approving her own: 403');
[$c, $b] = req_off($priya, $vac, $dd(6), $dd(6));
ok($c === 422 && msg($b) === 'There is already time off asked for or approved then.', 'a second request over the same day: 422 "' . msg($b) . '"');
[$c, $b] = req_off($mara, $unpaid, $dd(5), $dd(5));
$r8 = (int) $b['record_id'];
[$c, $b] = act($mara, '/time-off/approve.php', ['request' => $r8]);
ok($c === 403 && msg($b) === 'You cannot decide your own time off.', 'Mara approving her own: 403 "' . msg($b) . '"');
[$c, $b] = act($mara, '/time-off/decline.php', ['request' => $r8]);
ok($c === 403, 'nor decline it');
[$c, $b] = act($owner, '/time-off/approve.php', ['request' => $r8]);
ok($c === 200, 'the owner approves it');
[$c, $b] = act($mara, '/time-off/cancel.php', ['request' => $r7]);
ok($c === 200 && status_off($r7) === 'cancelled', 'a manager cancels Priya\'s pending request: 200');
ok(count(array_filter(outbox_ref("time_off:$r7"), fn ($x) => (int) $x['member_id'] === 26 && str_contains($x['body'], 'cancelled'))) >= 1, 'and Priya is told');
$yday = date('Y-m-d', time() - 2 * 86400);
[$c, $b] = req_off($priya, $vac, $yday, $yday);
ok($c === 422 && msg($b) === 'That time is already over.', 'staff cannot ask for time already over: 422 "' . msg($b) . '"');
[$c, $b] = req_off($mara, $vac, $yday, $yday, ['member' => 26, 'hours' => 4]);
$r9 = (int) ($b['record_id'] ?? 0);
ok($c === 200 && (float) $b['hours'] === 4.0 && (int) one('SELECT member_id FROM time_off_requests WHERE id = :i', ['i' => $r9]) === 26, 'a manager may enter it for her (member=26, hours 4): 200 — past time is allowed for an approver');
[$c, $b] = act($priya, '/time-off/cancel.php', ['request' => $r9]);
ok($c === 422 && msg($b) === 'That time off is over.', 'Priya cancelling time that is over: 422 "' . msg($b) . '"');
[$c, $b] = req_off($lee, $vac, $dd(6), $dd(6), ['member' => 30]);
ok($c === 403, 'Lee asking on Ana\'s behalf: 403');
[$c, $b] = req_off($priya, $vac, $dd(6), $dd(6), ['hours' => 'many']);
ok($c === 422 && msg($b) === 'Hours must be a number above 0.', 'hours that are not a number: 422 "' . msg($b) . '"');
[$c, $b] = act($priya, '/time-off/request.php', ['time_off_type' => $vac, 'starts_at' => 'tomorrow', 'ends_at' => 'later']);
ok($c === 422 && str_starts_with(msg($b), 'Give the dates like'), 'dates that are not dates: 422 "' . msg($b) . '"');
[$c, $b] = act($priya, '/time-off/request.php', ['time_off_type' => $vac, 'from' => $dd(6), 'to' => $dd(5)]);
ok($c === 422 && msg($b) === 'The time off has to end after it starts.', 'to before from: 422 "' . msg($b) . '"');
[$c, $b] = act($priya, '/time-off/request.php', ['time_off_type' => $vac, 'starts_at' => $dd(6) . ' 09:00', 'ends_at' => $dd(6) . ' 13:00', 'note' => str_repeat('x', 501)]);
ok($c === 422 && msg($b) === 'A note may be up to 500 characters.', 'a note over 500 characters: 422');

echo "8. Who is off, filters, and pages\n";
[$c, $b] = act($mara, '/time-off/approve.php', ['request' => (int) one("SELECT id FROM time_off_requests WHERE member_id = 26 AND status = 'pending' ORDER BY id DESC LIMIT 1") ?: 0]);
[$c, $b] = req_off($ana, $unpaid, $dd(1), $dd(1));
$ra = (int) $b['record_id'];
act($mara, '/time-off/approve.php', ['request' => $ra]);
[$c, $d] = screen($mara, "/time-off?on={$dd(1)}&site=102");
ok($c === 200 && $d['view'] === 'day' && in_array('SMOKE Ana', array_map(fn ($x) => $x['member']['name'], $d['requests']), true), '"who is off" on a date (Mara): Ana is listed');
ok(count(array_filter($d['requests'], fn ($x) => $x['status'] !== 'approved')) === 0, 'and only approved time off');
[$c, $d] = screen($lee, "/time-off?on={$dd(1)}&site=102");
ok($c === 200 && $d['view'] === 'mine' && $d['requests'] === [], 'Lee (staff) asking the same: only his own — nothing');
[$c, $d] = screen($ana, "/time-off?on={$dd(1)}");
ok(count($d['requests']) === 1 && $d['requests'][0]['member']['name'] === 'SMOKE Ana', 'Ana sees only her own');
[$c, $d] = screen($mara, '/time-off?member=all&site=102');
ok($c === 200 && $d['view'] === 'all' && count($d['requests']) >= 4, 'Everyone (Mara): the restaurant\'s requests (' . count($d['requests']) . ')');
[$c, $d] = screen($mara, '/time-off?member=all&site=102&status=cancelled');
ok(count($d['requests']) >= 1 && count(array_filter($d['requests'], fn ($x) => $x['status'] !== 'cancelled')) === 0, 'the status filter keeps only cancelled');
[$c, $d] = screen($mara, "/time-off?member=all&site=102&from={$dd(1)}&to={$dd(1)}");
ok(count($d['requests']) >= 1 && count(array_filter($d['requests'], fn ($x) => !str_contains(json_encode($x), $dd(1)) && substr($x['starts_at'], 0, 10) > $dd(2))) === 0, 'the date filter narrows to that day');
[$c, $d] = screen($mara, '/time-off?member=26');
ok($c === 200 && $d['view'] === 'person' && count($d['requests']) >= 3 && count(array_filter($d['requests'], fn ($x) => $x['member']['name'] !== 'SMOKE Priya')) === 0, 'one person (Priya): only her requests');
[$c, $d] = screen($lee, '/time-off?member=all&site=102');
ok($c === 403, 'a staff member cannot ask for Everyone: 403');
[$c, $d] = screen($priya, '/time-off');
ok($c === 200 && count($d['requests']) >= 5 && count(array_filter($d['requests'], fn ($x) => $x['member']['name'] !== 'SMOKE Priya')) === 0, 'her own list holds only her requests');
ok(!isset($d['requests'][0]['balance']) || is_array($d['requests'][0]['balance']), 'the balance appears only for a kind that keeps one');
$html = html_entity_decode(page($priya, '/time-off')['body']);
ok(str_contains($html, 'id="time-off-new-btn"') && str_contains($html, 'id="time-off-balances-link"') && !str_contains($html, 'id="time-off-scope-all"') && !str_contains($html, 'id="time-off-types-link"'), 'staff get Ask and Balances, not Everyone or the types link');
$html = html_entity_decode(page($owner, '/time-off')['body']);
ok(str_contains($html, 'id="time-off-scope-all"') && str_contains($html, 'id="time-off-types-link"'), 'the owner also gets Everyone and "Types and blackout dates"');
[$c, $d] = screen($mara, '/time-off?member=all&site=102&page=2');
ok($c === 200 && $d['page'] === 2, 'a second page answers (page 2 of ' . count($d['requests']) . ' rows)');

echo "9. Balance adjustments\n";
$v0 = bal(26, $vac); $nl = count(ledger_rows(26, $vac));
[$c, $b] = act($mara, '/time-off/balance.php', ['member' => 26, 'time_off_type' => $vac, 'delta_hours' => 4, 'reason' => 'SMOKE bonus']);
ok($c === 403 && msg($b) === 'You may not change pay or balances here.', 'a manager without pay.edit: 403 "' . msg($b) . '"');
[$c, $b] = act($owner, '/time-off/balance.php', ['member' => 26, 'time_off_type' => $vac, 'delta_hours' => 10, 'reason' => 'SMOKE service award']);
$led = ledger_rows(26, $vac); $last = end($led);
$lid = (int) ($b['record_id'] ?? 0);
ok($c === 200 && bal(26, $vac) === $v0 + 10 && count($led) === $nl + 1 && $last['reason'] === 'grant' && $last['note'] === 'SMOKE service award' && preg_match('~#ledger-' . $lid . '$~', (string) $b['location']), 'balance_adjust +10 (the owner): 200, a `grant` in the ledger with the reason, the location ends in the ledger id');
[$c, $b] = act($owner, '/time-off/balance.php', ['member' => 26, 'time_off_type' => $vac, 'delta_hours' => -4, 'reason' => 'SMOKE correction']);
$led = ledger_rows(26, $vac); $last = end($led);
ok($c === 200 && bal(26, $vac) === $v0 + 6 && $last['reason'] === 'adjustment' && (float) $last['delta_hours'] === -4.0, '−4 is an `adjustment`');
$al = json_decode((string) one("SELECT after FROM activity_log WHERE action = 'balance.adjust' ORDER BY id DESC LIMIT 1"), true);
ok((function () use ($al) { $k = array_keys($al); sort($k); return $k === ['balance_hours', 'delta_hours', 'ledger_id', 'member_id', 'reason', 'type']; })() && (int) one("SELECT scope_id FROM activity_log WHERE action = 'balance.adjust' ORDER BY id DESC LIMIT 1") === 102, 'balance.adjust is logged with the site and only hours: ' . implode(', ', array_keys($al)));
[$c, $b] = act($owner, '/time-off/balance.php', ['member' => 26, 'time_off_type' => $vac, 'delta_hours' => -1000, 'reason' => 'SMOKE too much']);
ok($c === 422 && str_starts_with(msg($b), 'Not enough vacation / pto left'), 'more than the balance holds: 422 "' . msg($b) . '"');
foreach ([[['delta_hours' => 0, 'reason' => 'SMOKE none'], 'Give the change in hours: a positive number grants, a negative one removes.'], [['delta_hours' => 3], 'Give a reason of a few words (3 to 500 characters).'], [['delta_hours' => 3, 'reason' => 'no'], 'Give a reason of a few words (3 to 500 characters).']] as [$f, $why]) {
    [$c, $b] = act($owner, '/time-off/balance.php', ['member' => 26, 'time_off_type' => $vac] + $f);
    ok($c === 422 && msg($b) === $why, 'refused in words: "' . msg($b) . '"');
}
[$c, $b] = act($owner, '/time-off/balance.php', ['member' => 26, 'time_off_type' => $unpaid, 'delta_hours' => 3, 'reason' => 'SMOKE nothing to keep']);
ok($c === 422 && msg($b) === 'That kind of time off does not keep a balance.', 'a kind that keeps no balance: 422 "' . msg($b) . '"');
[$c, $b] = act($owner, '/time-off/balance.php', ['member' => 28, 'time_off_type' => $vac, 'delta_hours' => 3, 'reason' => 'SMOKE wrong place']);
ok($c === 404, 'a person who does not work there: 404');
foreach (q('SELECT member_id, type_id, balance_hours FROM time_off_balances') as $r) {
    if ((float) one('SELECT COALESCE(sum(delta_hours), 0) FROM time_off_ledger WHERE member_id = :m AND type_id = :t', ['m' => $r['member_id'], 't' => $r['type_id']]) !== (float) $r['balance_hours']) { $drift[] = $r; }
}
ok(!isset($drift), 'every balance in the database equals the sum of its ledger');

echo "10. Types and blackout dates\n";
[$c, $b] = act($owner, '/time-off/types/save.php', ['time_off_type' => $adv, 'name' => 'SMOKE Advance leave', 'allow_negative' => 'no']);
$t = q('SELECT name, paid, tracks_balance, allow_negative FROM time_off_types WHERE id = :i', ['i' => $adv])[0];
ok($c === 200 && $t['name'] === 'SMOKE Advance leave' && $t['paid'] && $t['tracks_balance'] && !$t['allow_negative'], 'a change keeps what it did not send: renamed, allow_negative off, paid and tracks_balance unchanged');
[$c, $b] = act($owner, '/time-off/types/save.php', ['site' => 102, 'name' => 'SMOKE Bad', 'tracks_balance' => 'no', 'allow_negative' => 'yes']);
ok($c === 422 && msg($b) === 'Only a kind that keeps a balance can go below zero.', 'allow_negative without a balance: 422 "' . msg($b) . '"');
[$c, $b] = act($mara, '/time-off/types/save.php', ['site' => 102, 'name' => 'SMOKE Nope']);
ok($c === 403, 'a manager without settings.manage: 403');
[$c, $b] = act($owner, '/time-off/types/save.php', ['site' => 102, 'name' => 'SMOKE Advance']);
$dup = (int) ($b['record_id'] ?? 0);
ok($c === 200 && one('SELECT key FROM time_off_types WHERE id = :i', ['i' => $dup]) === 'smoke_advance_2', 'a second kind with the same key gets its own (smoke_advance_2)');
$since = last_activity_id();
[$c, $b] = act($owner, '/time-off/types/archive.php', ['time_off_type' => $adv]);
ok($c === 200 && one('SELECT archived_at FROM time_off_types WHERE id = :i', ['i' => $adv]) !== null && (int) one("SELECT count(*) FROM activity_log WHERE id > :s AND action = 'timeoff_type.archive' AND scope_id = 102", ['s' => $since]) === 1, 'time_off_type_archive: 200, archived, logged with the site');
$html = html_entity_decode(page($priya, '/time-off/new')['body']);
ok(!str_contains($html, 'SMOKE Advance leave') && str_contains($html, 'Vacation / PTO'), 'an archived kind leaves the picker');
[$c, $b] = req_off($priya, $adv, $dd(6), $dd(6));
ok($c === 422, 'and cannot be asked for: 422');
$page = html_entity_decode(page($priya, "/time-off/$r3")['body']);
ok(str_contains($page, 'advance leave') || str_contains($page, 'Advance leave') || str_contains($page, 'SMOKE Advance'), 'but it stays on the old request');
[$c, $b] = act($owner, '/time-off/types/archive.php', ['time_off_type' => $adv]);
ok($c === 422, 'archiving twice: 422 "' . msg($b) . '"');
[$c, $b] = act($mara, '/time-off/types/archive.php', ['time_off_type' => $vac]);
ok($c === 403, 'a manager cannot archive: 403');
[$c, $d] = screen($owner, '/site/time-off?site=102');
ok($c === 200 && count($d['types']) >= 4 && count($d['blackout_dates']) === 1 && $d['blackout_dates'][0]['reason'] === "Valentine's Day" && $d['day_hours'] == 8, 'the types screen (JSON): the kinds, the blackout date and the hours a day');
$r = req('GET', '/site/time-off?site=102', ['jar' => $mara, 'headers' => JSONH]);
ok($r['code'] === 403, 'the types screen for a manager: 403');
[$c, $b] = act($owner, '/time-off/blackout/remove.php', ['blackout' => $bo]);
ok($c === 200 && (int) one('SELECT count(*) FROM blackout_dates WHERE id = :i', ['i' => $bo]) === 0 && (int) one("SELECT count(*) FROM activity_log WHERE action = 'blackout.remove' AND entity_id = :i AND scope_id = 102", ['i' => $bo]) === 1, 'blackout_remove: 200, gone, logged with the site');
[$c, $b] = req_off($priya, $vac, $day(2), $day(2));
ok($c === 200, 'and the date can be asked for again');
act($priya, '/time-off/cancel.php', ['request' => (int) $b['record_id']]);
echo "   — a blackout added later does not touch what was already asked\n";
[$c, $b] = req_off($priya, $vac, $dd(2), $dd(2)); $late = (int) $b['record_id'];
act($owner, '/time-off/blackout/save.php', ['site' => 102, 'on_date' => $dd(2), 'reason' => 'SMOKE late']);
[$c, $b] = act($mara, '/time-off/approve.php', ['request' => $late]);
ok($c === 200 && status_off($late) === 'approved', 'a request asked before the blackout can still be approved');
[$c, $b] = act($owner, '/time-off/blackout/remove.php', ['blackout' => 99999]);
ok($c === 404, 'removing a date that is not there: 404');
finish();
