<?php
/**
 * Proof — the records tools, part 1: restaurants, people, the schedule, the marketplace, the rules. For each tool: the right shape, the scoping (a restaurant
 * not held does not exist; a draft is the managers'; a person sees their own), the wage rule (a rate only with labor.view, or one's own), and the answer to
 * "who is on Friday?" on scratch data. Callers are the cast: Owner 1 (admin at both), Priya 26 / Ana 30 / Lee 31 (staff, Airport), Dana 32 (shift lead, Airport),
 * Mara 33 (manager, Airport), Pat 35 (planner: builds, no pay), Marco 27 (manager Downtown, staff Airport), Joe 34 (staff Downtown), Nobody 29 (no restaurant).
 */
require __DIR__ . '/lib.php';
$W = reset_p4();
$AIR = 102; $DT = 101;
$FRI = next_dow('America/Chicago', 5);
$FRI_DT = next_dow('America/New_York', 5);
foreach ([$AIR => $FRI, $DT => $FRI_DT] as $site => $d) { clear_day($site, $d); clear_day($site, (new DateTimeImmutable($d))->modify('+70 days')->format('Y-m-d')); }
admin_sql("DELETE FROM exchanges WHERE shift_id IN (SELECT id FROM shifts WHERE note LIKE 'SMOKE p4 %'); UPDATE staff_profiles SET is_minor = false, minor_until = NULL;
           DELETE FROM rule_overrides WHERE reason LIKE 'SMOKE p4%'; DELETE FROM schedule_templates WHERE name LIKE 'SMOKE p4%';");
$srv = $W['aSrv']; $bar = $W['aBar']; $dsrv = $W['dSrv'];
$ana = local_shift($AIR, $srv, 30, $FRI, '17:00', '22:00');
$lee = local_shift($AIR, $srv, 31, $FRI, '11:00', '15:00');
$dana = local_shift($AIR, $srv, 32, $FRI, '17:00', '22:00');
$open = local_shift($AIR, $srv, null, $FRI, '17:00', '22:00');
$joe = local_shift($DT, $dsrv, 34, $FRI_DT, '12:00', '16:00');
$draftWeekDay = (new DateTimeImmutable($FRI))->modify('+70 days')->format('Y-m-d');
$dwk = local_shift($AIR, $srv, 30, $draftWeekDay, '12:00', '16:00', ['draft' => true]);   // a week nobody published
$utc = fn (string $date, string $t, string $tz) => (new DateTimeImmutable("$date $t", new DateTimeZone($tz)))->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d\TH:i');

echo "1. Who is on Friday?\n";
$r = tool(33, 'who_is_on', ['site_id' => $AIR, 'date' => $FRI]);
$d = $r['data'];
ok(!$r['error'] && $d['site'] === 'SMOKE Airport' && $d['date'] === $FRI && $d['timezone'] === 'America/Chicago', "Mara asks who is on $FRI at Airport: the restaurant, the date, its zone");
$names = fn (array $rows) => array_values(array_map(fn ($x) => preg_replace('/^SMOKE /', '', $x['assignee_name']), $rows));
ok(count($d['working']) === 3 && array_diff($names($d['working']), ['Lee', 'Ana', 'Dana']) === [], 'working: Lee, Ana, Dana — ' . implode(', ', $names($d['working'])));
ok(count($d['open']) === 1 && $d['open'][0]['is_open'] === true, 'one open shift, listed apart');
ok($d['draft'] === [], 'nothing unpublished on a published Friday');
ok(count($d['by_position']['Server'] ?? []) === 3, 'by position: three servers');
$row = fn (array $rows, int $id) => array_values(array_filter($rows, fn ($x) => $x['shift_id'] === $id))[0] ?? [];
$a = $row($d['working'], $ana);
ok($a['starts_local'] === "{$FRI}T17:00" && $a['ends_local'] === "{$FRI}T22:00" && $a['timezone'] === 'America/Chicago' && substr($a['starts_utc'], 0, 16) === $utc($FRI, '17:00', 'America/Chicago'), 'times: the restaurant\'s local time with its zone name, and UTC');
ok($a['day_parts'] === ['Dinner'] && $row($d['working'], $lee)['day_parts'] === ['Lunch'], 'day-parts: Ana\'s shift is Dinner, Lee\'s Lunch');
$r = tool(30, 'who_is_on', ['site_id' => $AIR, 'date' => $FRI]); $d = $r['data'];
ok($names($d['working']) === $names(tdata(33, 'who_is_on', ['site_id' => $AIR, 'date' => $FRI])['working']), 'Ana sees the same published team schedule');
$dm = tdata(33, 'who_is_on', ['site_id' => $AIR, 'date' => $draftWeekDay]);
ok($dm['working'] === [] && count($dm['draft']) === 1 && $dm['draft'][0]['published'] === false && $dm['draft'][0]['assignee_name'] === 'SMOKE Ana', 'an UNPUBLISHED week: the manager sees the shift, marked as a draft and apart from those working');
$da = tool(30, 'who_is_on', ['site_id' => $AIR, 'date' => $draftWeekDay]);
ok($da['data']['working'] === [] && $da['data']['draft'] === [] && !str_contains($da['text'], 'SMOKE Ana'), 'Ana, whose own shift it is, sees nothing of it until it is published');
$d = tdata(33, 'who_is_on', ['site_id' => $AIR, 'date' => $FRI, 'at' => '18:00']);
ok(array_diff($names($d['working']), ['Ana', 'Dana']) === [] && count($d['working']) === 2, 'at 18:00: Ana and Dana');
$d = tdata(33, 'who_is_on', ['site_id' => $AIR, 'date' => $FRI, 'at' => '12:00']);
ok($names($d['working']) === ['Lee'], 'at 12:00: Lee alone');
$d = tdata(33, 'who_is_on', ['site_id' => $AIR, 'date' => $FRI, 'at' => "{$FRI}T22:00"]);
ok($d['working'] === [], 'at 22:00 sharp: nobody (a shift ends when it ends)');
$d = tdata(33, 'who_is_on', ['site_id' => $AIR, 'at' => 'now']);
ok(is_array($d['working']) && $d['at'] !== null, "'now' answers (working: " . count($d['working']) . ')');
$d = tdata(33, 'who_is_on', ['site_id' => $AIR, 'date' => $FRI, 'position_id' => $bar]);
ok($d['working'] === [] && $d['open'] === [], 'position filter: nobody works Bar that Friday');
$d = tdata(34, 'who_is_on', ['site_id' => $DT, 'date' => $FRI_DT]);
ok($names($d['working']) === ['Joe'] && $d['timezone'] === 'America/New_York' && $d['working'][0]['starts_local'] === "{$FRI_DT}T12:00", 'Joe at Downtown: Joe, in New York time');
foreach ([[34, $AIR], [29, $AIR], [29, $DT], [26, $DT]] as [$who, $site]) {
    $r = tool($who, 'who_is_on', ['site_id' => $site, 'date' => $FRI]);
    ok($r['error'] && str_contains($r['text'], 'No such restaurant') && !str_contains($r['text'], 'Airport'), "member $who asking about restaurant $site (not held): it does not exist — no Airport in the answer");
}
$r = tool(33, 'who_is_on', ['site_id' => $AIR, 'date' => 'friday']);
ok($r['error'], 'a bad date is refused in words: ' . substr($r['text'], 0, 60));

echo "2. find_sites, find_staff, find_positions\n";
$s = tdata(33, 'find_sites');
ok(count($s) === 1 && $s[0]['site_id'] === $AIR && $s[0]['my_role'] === 'manager' && $s[0]['timezone'] === 'America/Chicago' && $s[0]['allow_swap'] === true && $s[0]['cutoff_minutes'] === 120, 'Mara holds Airport only: role, zone, trade switches');
ok(array_column(tdata(1, 'find_sites'), 'site_id') == [$DT, $AIR] || count(tdata(1, 'find_sites')) === 2, 'the owner holds both');
ok(tdata(29, 'find_sites') === [], 'Nobody holds none');
ok(count(tdata(27, 'find_sites', ['q' => 'down'])) === 1 && tdata(27, 'find_sites', ['q' => 'down'])[0]['my_role'] === 'manager', 'Marco: filter by name; his role differs per restaurant (manager Downtown, staff Airport)');
ok(array_column(array_filter(tdata(27, 'find_sites'), fn ($x) => $x['site_id'] === $AIR), 'my_role') === ['staff'], '...staff at Airport');
$st = tdata(30, 'find_staff', ['q' => 'smoke']);
ok(count($st) >= 3 && !array_filter($st, fn ($x) => $x['member_kind'] ?? false), 'find_staff answers');
$one = tdata(30, 'find_staff', ['q' => 'Lee'])[0] ?? [];
ok($one['member_id'] === 31 && $one['main_site_id'] === $AIR && $one['on_schedule'] === true && $one['positions'][0]['position'] === 'Server', 'Lee: id, main restaurant, on the schedule, positions');
$txt = tool(30, 'find_staff', ['limit' => 100])['text'];
ok(!preg_match('/@|example\.invalid|phone|email|\+1555/', $txt), 'find_staff carries no email or phone of anyone');
ok(array_column(tdata(30, 'find_staff', ['site_id' => $AIR, 'position_id' => $bar]), 'member_id') === [30], 'position filter: only Ana works Bar');
ok(array_column(tdata(34, 'find_staff', ['limit' => 100]), 'display_name') === array_values(array_intersect(array_column(tdata(34, 'find_staff', ['limit' => 100]), 'display_name'), ['SMOKE Joe', 'SMOKE Marco', 'SMOKE Sam', 'SMOKE Owner'])), 'Joe finds only people of Downtown (Joe, Marco, Sam, the owner) — no Airport staff');
ok(tdata(29, 'find_staff') === [] || array_column(tdata(29, 'find_staff'), 'member_id') === [29], 'Nobody finds no one but (at most) themself');
$p = tdata(30, 'find_positions');
ok(array_column($p, 'name') == ['Bar', 'Server'] && array_unique(array_column($p, 'site_id')) === [0 => $AIR] , 'positions: Bar and Server at Airport');
ok(array_filter($p, fn ($x) => $x['default_wage_rate'] !== null) === [], 'Ana (no labor.view): default_wage_rate is null on every position');
$p = tdata(33, 'find_positions');
ok(array_column($p, 'default_wage_rate', 'name') == ['Bar' => 23.19, 'Server' => 21.37], 'Mara (labor.view at Airport): the default rates');
$p = tdata(35, 'find_positions');
ok(array_filter($p, fn ($x) => $x['default_wage_rate'] !== null) === [], 'Pat (builds, no labor.view): no rate');
$p = tdata(27, 'find_positions');
$byS = []; foreach ($p as $x) { $byS[$x['site_id']] = $x['default_wage_rate']; }
ok($byS[$DT] === 22.83 && $byS[$AIR] === null, 'Marco: the Downtown rate (manager there) but not Airport\'s (staff there)');

echo "3. staff_profile\n";
$r = tdata(30, 'staff_profile');
ok($r['member_id'] === 30 && $r['profile_visible'] === true && count($r['sites']) === 1 && $r['sites'][0]['role_key'] === 'staff', 'Ana, herself: profile, restaurants with roles');
$pos = array_column($r['positions'], 'effective_rate', 'position');
ok($pos == ['Bar' => 23.19, 'Server' => 21.37], 'her own effective rates (no override: the position\'s default) — one\'s own wage is one\'s own');
$r = tdata(26, 'staff_profile');
ok(array_column($r['positions'], 'effective_rate', 'position') == ['Server' => 24.61] && $r['positions'][0]['wage_source'] === 'override', 'Priya\'s own rate overrides the default (24.61, override)');
$r = tool(30, 'staff_profile', ['member_id' => 26]);
ok(!$r['error'] && $r['data']['profile_visible'] === false && !str_contains($r['text'], '24.61') && !str_contains($r['text'], '21.37') && $r['data']['positions'][0]['effective_rate'] === null, 'Ana looks at Priya: the name and positions, no profile, no rate');
ok(!isset($r['data']['notes']) && !str_contains($r['text'], 'max_hours_week'), '...and none of the profile fields at all');
$r = tdata(33, 'staff_profile', ['member_id' => 26]);
ok($r['profile_visible'] === true && array_column($r['positions'], 'effective_rate', 'position') == ['Server' => 24.61], 'Mara (build + labor.view) sees Priya\'s profile and her rate');
$r = tdata(35, 'staff_profile', ['member_id' => 26]);
ok($r['profile_visible'] === true && $r['positions'][0]['effective_rate'] === null && !str_contains(json_encode($r), '24.61'), 'Pat (build, no labor.view): the profile, not the rate');
$r = tool(34, 'staff_profile', ['member_id' => 30]);
ok($r['error'], 'Joe cannot see an Airport person at all');
$r = tool(29, 'staff_profile', ['member_id' => 30]);
ok($r['error'], 'Nobody cannot either');

echo "4. certifications\n";
admin_sql("DELETE FROM certifications; INSERT INTO certifications (member_id, kind_id, issued_on, expires_on) SELECT 30, k.id, current_date - 300, current_date + 10 FROM certification_kinds k WHERE k.scope_id = 102 AND k.key = 'food_handler';
           INSERT INTO certifications (member_id, kind_id, issued_on, expires_on, verified_at, verified_by) SELECT 31, k.id, current_date - 900, current_date - 5, now(), 33 FROM certification_kinds k WHERE k.scope_id = 102 AND k.key = 'food_handler';
           INSERT INTO position_certifications (position_id, kind_id) SELECT $srv, k.id FROM certification_kinds k WHERE k.scope_id = 102 AND k.key = 'alcohol_service' ON CONFLICT DO NOTHING;");
$k = tdata(30, 'certification_kinds');
ok(array_column($k, 'name') == ['Alcohol service', 'Food handler'] && $k[0]['required_positions'] === ['Server'] && $k[0]['warn_days'] === 30, 'kinds: two, the alcohol one required for Server');
ok(count(tdata(30, 'certification_kinds', ['q' => 'food'])) === 1, 'kinds by name');
$c = tdata(30, 'certifications');
ok(count($c) === 1 && $c[0]['kind'] === 'Food handler' && $c[0]['due_soon'] === true && $c[0]['verified'] === false, 'Ana\'s card: due soon, unverified');
ok(tdata(30, 'certifications', ['member_id' => 31]) === [], 'Ana cannot read Lee\'s cards');
$c = tdata(33, 'certifications', ['member_id' => 31]);
ok(count($c) === 1 && $c[0]['expired'] === true && $c[0]['verified'] === true, 'Mara can: Lee\'s is expired, verified');
$c = tdata(33, 'certifications', ['q' => 'Ana food']);
ok(count($c) === 1 && $c[0]['member_id'] === 30 && str_contains($c[0]['label'], 'Ana'), 'look-up by words (how an action resolves a card): the id and a label');
$due = tdata(33, 'certifications_due');
$states = []; foreach ($due as $x) { $states[$x['display_name']][] = $x['state']; }
ok(in_array('expired', $states['SMOKE Lee'] ?? [], true) && in_array('due', $states['SMOKE Ana'] ?? [], true), 'due list (Mara): Lee expired, Ana due — ' . json_encode($states));
ok(count(array_filter($due, fn ($x) => $x['state'] === 'missing')) >= 1 && $due[0]['state'] === 'expired', 'servers missing the alcohol card are listed, most urgent (expired) first');
ok(array_column(tdata(33, 'certifications_due', ['state' => 'due']), 'member_id') === [30], 'state filter');
$mine = tdata(30, 'certifications_due');
ok(array_unique(array_column($mine, 'member_id')) === [0 => 30], 'Ana (staff) sees her own rows of the due list only');
ok(tdata(34, 'certifications_due') === [] || array_unique(array_column(tdata(34, 'certifications_due'), 'member_id')) === [0 => 34], 'Joe sees nothing of Airport');

echo "5. my_shifts, week_schedule, get_shift\n";
$jar = as_member(30);
[$c, $b] = act($jar, '/exchanges/offer.php', ['shift' => $ana]);
$xid = (int) ($b['record_id'] ?? 0);
ok($c === 200 && $xid > 0, "Ana offers her Friday shift through the app (exchange $xid)");
$r = tdata(30, 'my_shifts', ['from' => $FRI, 'to' => $FRI]);
$m = $row($r['shifts'], $ana);
ok($r['member_id'] === 30 && count($r['shifts']) === 1 && $m['label'] === 'SMOKE Ana ' . (new DateTimeImmutable($FRI))->format('D M d') . ' 17:00 Server', 'my_shifts: Ana\'s Friday (published only; her draft week shift is absent)');
ok($m['also_on'] == ['SMOKE Dana'] && ($m['exchange']['kind'] ?? '') === 'offer' && $m['exchange']['status'] === 'open', 'who else is on (Dana overlaps) and the exchange on it (an open offer)');
ok(!in_array($dwk, array_column(tdata(30, 'my_shifts', ['from' => $draftWeekDay, 'to' => $draftWeekDay])['shifts'], 'shift_id')), 'a shift in an unpublished week is not on her list');
ok(!tool(33, 'my_shifts', ['member_id' => 30, 'from' => $FRI, 'to' => $FRI])['error'], 'Mara may ask for Ana\'s shifts');
$r = tool(31, 'my_shifts', ['member_id' => 30]);
ok($r['error'] && str_contains($r['text'], 'manager'), 'Lee may not: "' . substr($r['text'], 0, 80) . '"');
ok(tdata(29, 'my_shifts')['shifts'] === [], 'Nobody has no shifts');
$r = tdata(33, 'week_schedule', ['site_id' => $AIR, 'week_start' => $FRI]);
ok($r['state'] === 'published' && $r['week_id'] > 0 && $r['timezone'] === 'America/Chicago', 'week_schedule (Mara): the week, published, with its week_id');
$day = array_values(array_filter($r['days'], fn ($x) => $x['date'] === $FRI))[0] ?? [];
ok(count($day['shifts']) === 4, 'Friday\'s shifts as the builder shows them: Ana, Lee, Dana and the open one (' . count($day['shifts']) . ')');
ok(isset($r['totals']['cost']) && $r['totals']['cost'] > 0 && $row($day['shifts'], $ana)['cost'] === 106.85, 'a manager with labor.view sees cost: Ana 5 h x 21.37 = 106.85 (' . ($row($day['shifts'], $ana)['cost'] ?? 'null') . ')');
ok($row($day['shifts'], $open)['cost'] === null, '...an open shift has none');
$r2 = tool(30, 'week_schedule', ['site_id' => $AIR, 'week_start' => $FRI]); $r2d = $r2['data'];
$day2 = array_values(array_filter($r2d['days'], fn ($x) => $x['date'] === $FRI))[0] ?? [];
ok(count($day2['shifts']) === 4 && !array_key_exists('cost', $r2d['totals']) && pay_in($r2d) === [], 'Ana: the same 4 shifts, no cost anywhere');
ok(!str_contains($r2['text'], '106.85') && array_filter(wages(), fn ($w) => str_contains($r2['text'], $w)) === [], 'and no fixture wage in her text');
$r3 = tdata(35, 'week_schedule', ['site_id' => $AIR, 'week_start' => $FRI]);
ok(pay_in($r3) === [] && count(array_values(array_filter($r3['days'], fn ($x) => $x['date'] === $FRI))[0]['shifts']) === 4, 'Pat (builds, no pay): the week, no cost');
$r = tdata(33, 'week_schedule', ['site_id' => $AIR, 'week_start' => $draftWeekDay]);
ok($r['state'] === 'draft' && $r['totals']['shifts'] === 1, 'Mara sees the unpublished week as a draft');
$r = tdata(30, 'week_schedule', ['site_id' => $AIR, 'week_start' => $draftWeekDay]);
ok($r['week'] === null && !str_contains(json_encode($r), 'SMOKE Ana'), 'Ana is told no such week — a draft is the managers\'');
$r = tool(34, 'week_schedule', ['site_id' => $AIR]);
ok($r['error'], 'Joe: Airport does not exist');
$r = tdata(33, 'week_schedule', ['site_id' => $AIR, 'week_start' => $FRI, 'q' => 'Ana']);
ok(count(array_merge(...array_column($r['days'], 'shifts'))) >= 1 && array_unique(array_column(array_merge(...array_column($r['days'], 'shifts')), 'assignee_name')) === [0 => 'SMOKE Ana'], 'q narrows to one person');
$r = tdata(33, 'week_schedule', ['q' => 'Ana Friday']);
$ids = array_column($r, 'shift_id');
ok(in_array($ana, $ids, true) && array_unique(array_column($r, 'assignee_name')) === [0 => 'SMOKE Ana'] && !in_array($dwk, $ids, true), 'RESOLVE MODE (q alone, as the kernel\'s resolver calls): a plain list with shift_id — Ana\'s Friday found, her draft week not');
foreach ($r as $x) { if (date('l', strtotime(substr($x['starts_local'], 0, 10))) !== 'Friday') { ok(false, 'a non-Friday in "Ana Friday": ' . $x['starts_local']); } }
$r = tdata(33, 'week_schedule', ['q' => $FRI]);
ok(count($r) === 1 && $r[0]['week_id'] > 0 && !isset($r[0]['shift_id']) && str_contains($r[0]['label'], 'SMOKE Airport'), 'a date alone names a WEEK (week_id, a label), not a shift');
ok(tdata(34, 'week_schedule', ['q' => 'Ana Friday']) === [], 'Joe resolving "Ana Friday": nothing (Airport is not his)');
$r = tool(33, 'week_schedule', []);
ok($r['error'], 'neither site nor q: told what to give');
$r = tdata(33, 'get_shift', ['shift_id' => $ana]);
ok($r['shift']['shift_id'] === $ana && $r['shift']['assignee_name'] === 'SMOKE Ana' && $r['shift']['cost'] === 106.85 && is_array($r['rule_warnings']), 'get_shift (Mara): the shift, its cost, its rule warnings');
ok(count($r['exchanges']) === 1 && $r['exchanges'][0]['kind'] === 'offer' && $r['exchanges'][0]['status'] === 'open', '...and its live exchange');
$r = tool(31, 'get_shift', ['shift_id' => $ana]);
ok(!$r['error'] && $r['data']['shift']['cost'] === null && $r['data']['rule_warnings'] === [], 'Lee looks at Ana\'s shift: no cost, no rule warnings (not his to ask)');
$r = tool(30, 'get_shift', ['shift_id' => $dwk]);
ok($r['error'], 'Ana cannot open her own shift while its week is a draft');
$r = tool(34, 'get_shift', ['shift_id' => $ana]);
ok($r['error'], 'Joe cannot open an Airport shift');
$r = tool(35, 'get_shift', ['shift_id' => $dwk]);
ok(!$r['error'] && $r['data']['shift']['published'] === false, 'Pat (builds) opens the draft shift');

echo "6. The marketplace\n";
$m = tdata(31, 'marketplace');
ok(count($m) === 1 && $m[0]['exchange_id'] === $xid && $m[0]['kind'] === 'offer' && $m[0]['from_name'] === 'SMOKE Ana', 'Lee (main restaurant Airport, works Server) sees Ana\'s offer');
ok($m[0]['can_take'] === true && $m[0]['why_not'] === [], 'and may take it');
$m0 = tdata(30, 'marketplace', ['mine' => true]);
ok(count($m0) === 1 && $m0[0]['can_take'] === false && str_contains(implode(' ', $m0[0]['why_not']), 'own shift'), 'Ana: her own offer, mine=true, cannot take it (own shift)');
$m = tdata(27, 'marketplace');
ok($m === [] || ($m[0]['can_take'] === false), 'Marco (main restaurant Downtown) does not get to take an Airport offer');
ok(tdata(34, 'marketplace') === [], 'Joe sees no Airport offer at all');
ok(tdata(29, 'marketplace') === [], 'Nobody sees none');
$m = tdata(33, 'marketplace', ['site_id' => $AIR]);
ok(count($m) === 1 && $m[0]['starts_local'] === "{$FRI}T17:00" && $m[0]['label'] !== '' && $m[0]['position_name'] === 'Server', 'Mara sees it too, with its times in Airport time and a label');
$m = tdata(33, 'marketplace', ['q' => 'Ana']);
ok(count($m) === 1, 'q alone finds the live exchange by the holder\'s name (how an action resolves an exchange)');
ok(tdata(33, 'marketplace', ['kind' => 'swap']) === [] && count(tdata(33, 'marketplace', ['kind' => 'offer'])) === 1, 'kind filter');
$r = tool(33, 'marketplace', ['kind' => 'trade']);
ok($r['error'], 'a bad kind is refused in words');
admin_sql("UPDATE site_settings SET allow_pickup = false WHERE scope_id = $AIR");
$m = tdata(31, 'marketplace');
ok($m[0]['can_take'] === false && str_contains(implode(' ', $m[0]['why_not']), 'pick-ups'), 'a restaurant that turned pick-ups off: Lee is told why he cannot');
admin_sql("UPDATE site_settings SET allow_pickup = true WHERE scope_id = $AIR");
[$c, $b] = act(as_member(31), '/exchanges/claim.php', ['exchange' => $xid]);
$m = tdata(31, 'marketplace', ['mine' => true, 'status' => 'all']);
ok($c === 200 && count($m) >= 1, 'Lee claims through the app (status ' . one('SELECT status FROM exchanges WHERE id = ' . $xid) . ')');
$m = tdata(33, 'marketplace', ['status' => 'all', 'site_id' => $AIR]);
ok(count($m) === 1 && in_array($m[0]['status'], ['approved', 'pending_approval', 'open'], true), 'status=all lists history');

echo "7. coverage_candidates, check_assignment, week_warnings, overrides, hours\n";
$open2 = local_shift($AIR, $srv, null, $FRI, '19:00', '23:00', ['break' => 0]);
$r = tdata(33, 'coverage_candidates', ['shift_id' => $open2]);
$ids = array_column($r['candidates'], 'member_id');
ok(in_array(31, $ids, true) && !in_array(30, $ids, true) && !in_array(32, $ids, true) && !in_array(27, $ids, true), 'candidates for a 19:00 gap: free, main-restaurant staff (Lee yes; Ana and Dana are working; Marco\'s main is Downtown)');
ok($r['candidates'] === array_values($r['candidates']) && $r['note'] === null, 'a list, no note');
$r = tdata(32, 'coverage_candidates', ['shift_id' => $open2]);
ok(count($r['candidates']) >= 1, 'Dana (shift lead: coverage.fill) may ask');
$r = tdata(30, 'coverage_candidates', ['shift_id' => $open2]);
ok($r['candidates'] === [] && str_contains((string) $r['note'], 'coverage.fill'), 'Ana (staff) gets no candidates and is told which right it needs');
ok(tool(34, 'coverage_candidates', ['shift_id' => $open2])['error'], 'Joe: no such shift');
admin_sql("UPDATE staff_profiles SET is_minor = true, minor_until = current_date + 300 WHERE member_id = 31");
$r = tdata(33, 'check_assignment', ['member_id' => 31, 'site_id' => $AIR, 'position_id' => $srv, 'starts_at' => "{$FRI}T18:00", 'ends_at' => "{$FRI}T23:30"]);
ok($r['allowed'] === false && count($r['hard']) >= 1, 'check_assignment (Mara): a minor working past the curfew — hard: ' . ($r['hard'][0]['rule_key'] ?? '?'));
$r = tdata(33, 'check_assignment', ['member_id' => 31, 'site_id' => $AIR, 'position_id' => $srv, 'starts_at' => "{$FRI}T16:00", 'ends_at' => "{$FRI}T19:00"]);
ok($r['allowed'] === true, 'an early evening shift is allowed for the minor');
$r = tdata(31, 'check_assignment', ['member_id' => 31, 'site_id' => $AIR, 'position_id' => $srv, 'starts_at' => "{$FRI}T18:00", 'ends_at' => "{$FRI}T23:30"]);
ok($r['allowed'] === false, 'Lee may check his own');
$r = tool(30, 'check_assignment', ['member_id' => 31, 'site_id' => $AIR, 'position_id' => $srv, 'starts_at' => "{$FRI}T18:00", 'ends_at' => "{$FRI}T23:30"]);
ok($r['error'], 'Ana may not check Lee\'s');
$r = tdata(33, 'check_assignment', ['member_id' => 31, 'shift_id' => $open2]);
ok($r['allowed'] === false, 'check_assignment with a shift_id (open 19:00-23:00 for the minor): hard');
$r = tool(33, 'check_assignment', ['member_id' => 31]);
ok($r['error'], 'neither a shift nor a plan: told what to give');
$bad = local_shift($AIR, $srv, 31, (new DateTimeImmutable($FRI))->modify('+1 day')->format('Y-m-d'), '18:00', '23:30');
admin_sql("INSERT INTO rule_overrides (scope_id, shift_id, member_id, rule_key, message, reason, overridden_by, context) SELECT $AIR, $bad, 31, rule_key, message, 'SMOKE p4 the kitchen is short', 33, 'build' FROM ts_assignment_warnings(31, $AIR, $srv, (SELECT starts_at FROM shifts WHERE id = $bad), (SELECT ends_at FROM shifts WHERE id = $bad), 0, $bad) WHERE severity = 'hard' LIMIT 1");
$r = tdata(33, 'week_warnings', ['site_id' => $AIR, 'week_start' => $FRI]);
$mine = array_values(array_filter($r['warnings'], fn ($x) => $x['shift_id'] === $bad));
ok($r['count'] >= 1 && count($mine) >= 1 && $mine[0]['severity'] === 'hard' && ($mine[0]['override']['reason'] ?? '') === 'SMOKE p4 the kitchen is short', 'week_warnings (Mara): the minor\'s late shift, hard, with the override already recorded (who, why)');
ok($r['warnings'][0]['severity'] === 'hard', 'hard first');
$r = tdata(30, 'week_warnings', ['site_id' => $AIR, 'week_start' => $FRI]);
ok($r['count'] === 0 && str_contains((string) $r['note'], 'schedule.build'), 'Ana: nothing, and the right it needs');
ok(tdata(35, 'week_warnings', ['site_id' => $AIR, 'week_start' => $FRI])['count'] >= 1, 'Pat (builds) may');
ok(tool(34, 'week_warnings', ['site_id' => $AIR, 'week_start' => $FRI])['data']['count'] ?? 0 === 0, 'Joe: nothing of Airport');
$o = tdata(33, 'overrides', ['member_id' => 31]);
ok(count($o) === 1 && $o[0]['member_name'] === 'SMOKE Lee' && $o[0]['overridden_by_name'] === 'SMOKE Mara' && $o[0]['reason'] === 'SMOKE p4 the kitchen is short', 'overrides (Mara): who, for whom, why');
ok(tdata(30, 'overrides') === [] && tdata(31, 'overrides') === [], 'staff see none');
ok(count(tdata(33, 'overrides', ['rule_key' => $o[0]['rule_key'], 'from' => date('Y-m-d', time() - 86400), 'to' => date('Y-m-d')])) === 1, 'filters by rule and period');
admin_sql("UPDATE site_settings SET overtime_weekly_hours = 6 WHERE scope_id = $AIR");
$h = tdata(30, 'hours_this_week', ['week_start' => $FRI]);
ok(count($h) === 1 && $h[0]['member_id'] === 30 && $h[0]['scheduled_hours'] >= 5 && $h[0]['overtime_weekly_hours'] == 6, 'hours_this_week: Ana\'s own row against the overtime line');
$h = tdata(33, 'hours_this_week', ['week_start' => $FRI, 'near_overtime' => true]);
ok(count($h) >= 2 && count(array_unique(array_column($h, 'member_id'))) >= 2, 'a manager: everyone near or over the line (' . count($h) . ')');
$h = tdata(31, 'hours_this_week', ['week_start' => $FRI, 'near_overtime' => true]);
ok(array_unique(array_column($h, 'member_id')) === [] || array_unique(array_column($h, 'member_id')) === [0 => 31], 'Lee asking for everyone gets only himself');
ok(tdata(30, 'hours_this_week', ['week_start' => $FRI, 'member_id' => 32]) === [], 'Ana asking for Dana\'s hours: nothing');
ok(pay_in(tdata(33, 'hours_this_week', ['week_start' => $FRI, 'near_overtime' => true])) === [], 'hours, never pay');
admin_sql("UPDATE site_settings SET overtime_weekly_hours = 40 WHERE scope_id = $AIR; UPDATE staff_profiles SET is_minor = false, minor_until = NULL");

echo "8. find_templates\n";
admin_sql("INSERT INTO schedule_templates (scope_id, name, created_by) VALUES ($AIR, 'SMOKE p4 Slow week', 33);
           INSERT INTO template_shifts (template_id, position_id, weekday, starts_at, ends_at, break_minutes, assignee_member_id) SELECT id, $srv, 5, '17:00', '22:00', 0, 30 FROM schedule_templates WHERE name = 'SMOKE p4 Slow week'");
$t = tdata(33, 'find_templates');
ok(count($t) === 1 && $t[0]['name'] === 'SMOKE p4 Slow week' && $t[0]['shift_count'] === 1, 'Mara: the template with its shift count');
$t = tdata(33, 'find_templates', ['template_id' => $t[0]['template_id']]);
ok($t[0]['shifts'][0]['position'] === 'Server' && $t[0]['shifts'][0]['assignee_name'] === 'SMOKE Ana' && $t[0]['shifts'][0]['weekday'] === 5, 'with template_id: what it holds');
ok(tdata(30, 'find_templates') === [] && tdata(34, 'find_templates') === [], 'staff and other restaurants\' people see no templates');
ok(count(tdata(33, 'find_templates', ['q' => 'slow'])) === 1 && tdata(33, 'find_templates', ['q' => 'zzz']) === [], 'q is the resolver\'s door: a list');
finish();
