<?php
/** Proof — positions (spec "Proof": Positions): add, rename and recolour; a duplicate live name is 422; archiving one an upcoming shift uses is 422, one nobody uses archives and leaves the pickers; the form and the default-rate form are per right. */
require __DIR__ . '/lib.php';
$W = reset4();
$owner = as_member(1, 102); $mara = as_member(33); $pat = as_planner(); $priya = as_member(26); $dee = as_dee();
$since = last_activity_id();
echo "1. Add, rename, recolour\n";
[$c, $b] = act($owner, '/positions/save.php', ['site' => 102, 'name' => 'SMOKE Host', 'area' => 'front', 'color' => '#2ca58d', 'sort_order' => 5]);
$host = (int) ($b['record_id'] ?? 0);
ok($c === 200 && $host > 0 && str_ends_with((string) $b['location'], "#position-$host") && str_contains((string) $b['location'], '/positions/?site=102'), 'position_save: 200, record_id, the location ends in the record (' . ($b['location'] ?? '') . ')');
$r = q('SELECT name, area, color, sort_order, scope_id, default_wage_rate FROM positions WHERE id = :i', ['i' => $host])[0] ?? [];
ok($r['name'] === 'SMOKE Host' && $r['color'] === '#2ca58d' && (int) $r['scope_id'] === 102 && $r['default_wage_rate'] === null, 'stored at Airport with no rate');
[$c, $b] = act($owner, '/positions/save.php', ['position' => $host, 'name' => 'SMOKE Head host', 'color' => '#ff8800']);
$r = q('SELECT name, area, color, sort_order FROM positions WHERE id = :i', ['i' => $host])[0];
ok($c === 200 && $r['name'] === 'SMOKE Head host' && $r['color'] === '#ff8800' && $r['area'] === 'front' && (int) $r['sort_order'] === 5, 'rename and recolour: what was left out (area, order) stayed');
$row = q("SELECT scope_id, before, after FROM activity_log WHERE action = 'position.save' AND entity_id = :i ORDER BY id DESC LIMIT 1", ['i' => $host])[0];
$af = json_decode($row['after'], true); $bf = json_decode($row['before'], true);
ok((int) $row['scope_id'] === 102 && $af['name'] === 'SMOKE Head host' && $bf['name'] === 'SMOKE Host' && $af['color'] === '#ff8800' && !array_key_exists('default_wage_rate', $af), 'position.save carries the site and before/after of name, area, colour, order, certification kinds — no rate');
[$c, $d] = screen($owner, '/positions/?site=102');
ok($c === 200 && in_array('SMOKE Head host', array_column($d['positions'], 'name'), true), 'it is on the positions list');
[$c, $b] = act($owner, '/positions/save.php', ['site' => 102, 'name' => 'smoke head host']);
ok($c === 422 && str_contains(msg($b), 'is already a position here'), 'a duplicate live name (any case) at the same restaurant: 422 "' . msg($b) . '"');
[$c, $b] = act($owner, '/positions/save.php', ['site' => 101, 'name' => 'SMOKE Head host']);
ok($c === 200, 'the same name at another restaurant is fine');
$otherHost = (int) $b['record_id'];
foreach ([['name' => ''], ['name' => 'SMOKE X', 'area' => 'roof'], ['name' => 'SMOKE X', 'color' => 'red'], ['name' => 'SMOKE X', 'sort_order' => '-4']] as $bad) { [$c, $b] = act($owner, '/positions/save.php', ['site' => 102] + $bad); ok($c === 422, 'invalid ' . json_encode($bad) . ': 422 (' . msg($b) . ')'); }
echo "2. The forms are per right\n";
$codes = [];
foreach (['Mara' => $mara, 'Pat' => $pat, 'Priya' => $priya] as $who => $jar) { [$c] = act($jar, '/positions/save.php', ['site' => 102, 'name' => 'SMOKE Nope']); [$c2] = act($jar, '/positions/archive.php', ['position' => $host]); $codes[$who] = [$c, $c2]; }
ok($codes['Mara'] === [403, 403] && $codes['Pat'] === [403, 403] && $codes['Priya'] === [403, 403], 'without settings.manage — a manager, a planner, staff: save and archive are 403 (' . json_encode($codes) . ')');
[$c] = act($dee, '/positions/save.php', ['position' => $host, 'name' => 'SMOKE Hijack']);
ok($c === 404 && q('SELECT name FROM positions WHERE id = :i', ['i' => $host])[0]['name'] === 'SMOKE Head host', 'Dee (Downtown) cannot change an Airport position: 404');
$pg = page($mara, '/positions/?site=102')['body'];
ok(!str_contains($pg, 'id="positions-list-add-btn"') && !str_contains($pg, 'position-' . $host . '-archive-btn') && !str_contains($pg, 'position-' . $host . '-edit-btn') && str_contains($pg, 'SMOKE Head host'), 'Mara\'s positions page: no Add, no Change, no Archive');
$pg = page($owner, '/positions/?site=102')['body'];
ok(str_contains($pg, 'id="positions-list-add-btn"') && str_contains($pg, 'position-' . $host . '-archive-btn') && str_contains($pg, 'position-' . $host . '-rate-form'), 'the owner\'s has Add, Archive and the default-rate form');
ok(req('GET', '/positions/new?site=102', ['jar' => $mara])['code'] === 403 && req('GET', "/positions/$host/edit", ['jar' => $mara])['code'] === 403 && req('GET', '/positions/new?site=102', ['jar' => $owner])['code'] === 200 && req('GET', "/positions/$host/edit", ['jar' => $owner])['code'] === 200, 'the form screens: 403 for Mara, 200 for the owner');
ok(req('GET', '/positions/?site=102', ['jar' => $priya])['code'] === 403 && req('GET', '/staff/?site=102', ['jar' => $priya])['code'] === 403 && req('GET', '/certifications/?site=102', ['jar' => $priya])['code'] === 403, 'staff have none of Positions, Staff, Certifications: 403');
ok(req('GET', '/positions/?site=102', ['jar' => $dee])['code'] === 404, 'a restaurant the caller does not hold: 404');
echo "3. Archiving\n";
ok(picker_has($owner, 102, 'SMOKE Head host'), 'before archiving it is in the shift form\'s position picker');
$ws = wk(91);
$sid = pub_shift(102, $host, null, $ws, 3, '17:00', '23:00');
[$c, $b] = act($owner, '/positions/archive.php', ['position' => $host]);
ok($c === 422 && str_contains(msg($b), 'is on 1 upcoming shift') && q('SELECT archived_at FROM positions WHERE id = :i', ['i' => $host])[0]['archived_at'] === null, 'a position an upcoming shift uses: 422 "' . msg($b) . '"');
admin_sql("UPDATE shifts SET status = 'cancelled', cancelled_at = now(), cancel_reason = 'SMOKE' WHERE id = $sid");
[$c, $b] = act($owner, '/positions/archive.php', ['position' => $host]);
ok($c === 200 && q('SELECT archived_at FROM positions WHERE id = :i', ['i' => $host])[0]['archived_at'] !== null, 'once the shift is cancelled it archives');
[$c, $b] = act($owner, '/positions/archive.php', ['position' => $host]);
ok($c === 422 && str_contains(msg($b), 'already archived'), 'again: 422 "already archived"');
[$c, $d] = screen($owner, '/positions/?site=102');
ok(!in_array('SMOKE Head host', array_column($d['positions'], 'name'), true) && !picker_has($owner, 102, 'SMOKE Head host'), 'it leaves the list and the shift form\'s picker');
ok((int) one('SELECT position_id FROM shifts WHERE id = :i', ['i' => $sid]) === $host, 'and stays on the old shift');
$row = q("SELECT scope_id, after FROM activity_log WHERE action = 'position.archive' AND entity_id = :i", ['i' => $host])[0] ?? null;
ok($row !== null && (int) $row['scope_id'] === 102, 'position.archive is logged with the site');
[$c, $b] = act($owner, '/positions/save.php', ['position' => $host, 'name' => 'SMOKE Renamed']);
ok($c === 422 && msg($b) === 'That position is archived.', 'an archived position cannot be changed: 422');
echo "4. Certifications a position needs, and the wage-blind log\n";
$fh = kind(102, 'food_handler'); $al = kind(102, 'alcohol_service');
[$c, $b] = act($owner, '/positions/save.php', ['site' => 102, 'name' => 'SMOKE Runner', 'certifications' => [$fh, 'Alcohol service']]);
$run = (int) $b['record_id'];
ok($c === 200 && q('SELECT kind_id FROM position_certifications WHERE position_id = :p ORDER BY kind_id', ['p' => $run]) === q('SELECT id AS kind_id FROM certification_kinds WHERE id IN (:a, :b) ORDER BY id', ['a' => $fh, 'b' => $al]), 'certifications given by id and by name both resolve');
[$c, $d] = screen($owner, '/positions/?site=102');
$card = array_values(array_filter($d['positions'], fn ($p) => $p['name'] === 'SMOKE Runner'))[0] ?? [];
ok(($card['certifications'] ?? []) == ['Alcohol service', 'Food handler'] || ($card['certifications'] ?? []) == ['Food handler', 'Alcohol service'], 'the card lists what it needs');
$text = json_encode(q("SELECT action, before, after FROM activity_log WHERE action LIKE 'position.%' AND id > :s", ['s' => $since]));
ok(wage_leaks($text) === [] && !str_contains($text, 'wage') && !str_contains($text, 'rate'), 'the position log rows mention no wage or rate');
finish();
function picker_has(string $jar, int $site, string $name): bool { return str_contains(page($jar, "/shifts/new?site=$site")['body'], '>' . $name . '<'); }
