<?php
/** Proof — agents and the action token (spec "Proof", 9): a person's action token acts as that person (her own shift only); an agent's run token acts at the action's site; every row source agent with the run's request id. */
require __DIR__ . '/lib.php';
$W = world();
$key = need('ACTION_TOKEN_KEY'); $relayKey = need('ACTIONS_RELAY_KEY');
$person = fn (int $m, int $ttl = 300): string => ($p = $m . '.' . (time() + $ttl)) . '.' . hash_hmac('sha256', $p, $key);
$run = fn (int $m, int $runId): string => ($p = $m . '.' . (time() + 300) . '.' . $runId) . '.' . hash_hmac('sha256', 'run:' . $p, $key);
$relay = fn (string $tok): string => hash_hmac('sha256', $tok, $relayKey);
$post = fn (string $path, array $form, array $h): array => (function () use ($path, $form, $h) { $r = req('POST', $path, ['headers' => array_merge(JSONH, $h), 'form' => $form]); return [$r['code'], json_decode($r['body'], true) ?? [], $r]; })();
as_member(26); as_member(30); as_member(31); as_member(27, 101);

echo "1. A person's action token (the assistant acts as her)\n";
$s = mkshift(102, srv(), 26, 1600);
$other = mkshift(102, srv(), 30, 1620);
$since = last_activity_id();
[$c, $b, $r] = $post('/exchanges/offer.php', ['shift' => $s], ['X-Action-Token: ' . $person(26)]);
ok($c === 200 && ($b['ok'] ?? false) && preg_match('~^/exchanges/\d+$~', (string) ($b['location'] ?? '')) && !str_contains($r['headers'], 'Set-Cookie'), 'Priya\'s token offers HER shift (no CSRF token, no cookie set): location ends in the exchange id');
$row = q("SELECT source, actor_member_id, scope_id, agent_run_id FROM activity_log WHERE action = 'exchange.offer' AND id > :s", ['s' => $since])[0] ?? [];
ok(($row['source'] ?? '') === 'assistant' && (int) ($row['actor_member_id'] ?? 0) === 26 && (int) ($row['scope_id'] ?? 0) === 102, 'the row is source assistant (a person\'s own token, no run), her id, the site');
[$c, $b] = $post('/exchanges/offer.php', ['shift' => $other], ['X-Action-Token: ' . $person(26)]);
ok($c === 422 && msg($b) === 'Only the person working a shift can offer it.', 'the same token offering Ana\'s shift: 422 "Only the person working a shift can offer it."');
[$c, $b] = $post('/exchanges/offer.php', ['shift' => $W['j1']], ['X-Action-Token: ' . $person(26)]);
ok($c === 404 && msg($b) === 'Shift not found.', 'and a Downtown shift: 404 — the site comes from the shift, checked against what she holds');
[$c, $b] = $post('/exchanges/offer.php', ['shift' => $other], ['X-Action-Token: ' . $person(26, -5)]);
ok($c === 401, 'an expired token: 401');
$x = (int) one("SELECT id FROM exchanges WHERE shift_id = :s", ['s' => $s]);
[$c, $b] = $post('/exchanges/claim.php', ['exchange' => $x], ['X-Action-Token: ' . $person(31)]);
ok($c === 200 && ($b['outcome'] ?? '') === 'approved' && holder_of($s) === 31, 'shift_pickup under Lee\'s token behaves as the screen: approved, the shift is Lee\'s');
$s2 = mkshift(102, srv(), 30, 1640);
$x2 = offer(as_member(30), $s2);
[$c, $b] = $post('/exchanges/claim.php', ['exchange' => $x2], ['X-Action-Token: ' . $person(27)]);
ok($c === 422 && msg($b) === 'You can pick up shifts only at your main restaurant.', 'Marco\'s token claiming an Airport offer: 422, the screen\'s sentence');
q("UPDATE exchanges SET status = 'cancelled' WHERE id = :x", ['x' => $x2]);

echo "2. An agent under a run token, granted at Airport\n";
admin_sql("INSERT INTO members (id, member_kind, display_name, business_role, status, capability, roles) VALUES (901, 'agent', 'SMOKE Scheduler agent', 'user', 'active', 'write', '{staff}') ON CONFLICT DO NOTHING;
           INSERT INTO member_site_roles (member_id, scope_id, role_key, roles, capability) VALUES (901, 102, 'staff', '{staff}', 'write') ON CONFLICT DO NOTHING;
           INSERT INTO staff_profiles (member_id, main_scope_id) VALUES (901, 102) ON CONFLICT DO NOTHING;
           INSERT INTO staff_positions (member_id, position_id) VALUES (901, " . srv() . ") ON CONFLICT DO NOTHING;");
kernel_state(function ($s) { $s['facts']['501'] = ['valid' => true, 'is_agent' => true, 'member_id' => 901, 'run_id' => 501, 'request_id' => 'req-run-501', 'trigger' => 'chat', 'endpoints' => [['name' => 'Records MCP']]]; return $s; });
$tok = $run(901, 501);
$hdr = ['X-Action-Token: ' . $tok, 'X-Action-Relay: ' . $relay($tok)];
$o = mkshift(102, srv(), null, 1700);
$xo = (int) one('SELECT ts_exchange_create(:k, :s, :by, NULL, NULL, NULL)', ['k' => 'open', 's' => $o, 'by' => 32]);
$since = last_activity_id();
[$c, $b] = $post('/exchanges/claim.php', ['exchange' => $xo], $hdr);
ok($c === 200 && ($b['outcome'] ?? '') === 'approved' && holder_of($o) === 901, 'shift_pickup through the run token: approved, the shift is the agent\'s');
$rows = q("SELECT action, source, agent_run_id, request_id, scope_id FROM activity_log WHERE id > :s AND action IN ('exchange.claim', 'shift.assign')", ['s' => $since]);
ok(count($rows) === 2 && count(array_filter($rows, fn ($r) => $r['source'] === 'agent' && (int) $r['agent_run_id'] === 501 && $r['request_id'] === 'req-run-501' && (int) $r['scope_id'] === 102)) === 2, 'every row (exchange.claim, shift.assign) is source agent, run 501, the run\'s own request id, the site 102');
[$c, $b] = $post('/exchanges/offer.php', ['shift' => $W['j1']], $hdr);
ok($c === 404, 'the agent offering/reaching a Downtown shift it is not granted at: 404');
$mine = mkshift(102, srv(), 901, 1720);
[$c, $b] = $post('/exchanges/offer.php', ['shift' => $mine], $hdr);
ok($c === 200 && (int) one("SELECT count(*) FROM activity_log WHERE action = 'exchange.offer' AND source = 'agent' AND scope_id = 102") === 1, 'it offers its own shift; the row is source agent');
[$c, $b] = $post('/exchanges/offer.php', ['shift' => $W['a2']], $hdr);
ok($c === 422 && msg($b) === 'Only the person working a shift can offer it.', 'and not Ana\'s: 422');
$r = req('GET', '/marketplace', ['headers' => array_merge(JSONH, $hdr)]);
ok($r['code'] === 403, 'an agent does not open the person\'s marketplace screen (people only): 403');
$r = req('POST', '/exchanges/claim.php', ['headers' => array_merge(JSONH, ['X-Action-Token: ' . $tok]), 'form' => ['exchange' => $xo]]);
ok($r['code'] === 401, 'a run token without the relay: 401');
kernel_state(function ($s) { unset($s['facts']); return $s; });
finish();
