<?php
/** Proof — approval follows the settings (spec "Proof", 5): pickup on_warning, give always/never, the approver's inbox, decline/approve, same-day shift lead, plain staff. */
require __DIR__ . '/lib.php';
$W = world();
$priya = as_member(26); $ana = as_member(30); $lee = as_member(31); $dana = as_member(32); $mara = as_member(33); $owner = as_member(1, 102);

echo "1. approval_pickup = on_warning: a soft warning sends the claim to a manager\n";
settings(102, ['approval_pickup' => 'on_warning']);
$l0 = mkshift(102, srv(), 31, 500);
$h = mkshift(102, srv(), 26, 510);           // 4 hours after Lee's shift: min_rest (soft)
$x = offer($priya, $h);
$since = last_activity_id();
[$c, $b] = claim($lee, $x);
ok($c === 202 || ($c === 200 && ($b['outcome'] ?? '') === 'pending_approval'), 'Lee\'s claim: outcome pending_approval (' . $c . ')');
ok(status_of($x) === 'pending_approval' && holder_of($h) === 26, 'the exchange waits for a manager and the shift has not moved');
$xr = q('SELECT warnings, needs_approval FROM exchanges WHERE id = :x', ['x' => $x])[0];
ok($xr['needs_approval'] && str_contains($xr['warnings'], 'Less than 10 hours between shifts.'), 'the exchange carries the soft warning for its approver');
[$c, $d] = screen($mara, '/approvals');
$row = array_values(array_filter($d['exchanges'] ?? [], fn ($e) => $e['exchange_id'] === $x))[0] ?? null;
ok($row !== null && $row['warnings'][0]['message'] === 'Less than 10 hours between shifts.', 'the approver\'s inbox (Mara) shows it with the warning');
$page = page($mara, '/approvals')['body'];
ok(str_contains($page, 'id="approval-card-' . $x . '-approve-btn"') && str_contains($page, 'id="approval-card-' . $x . '-decline-btn"') && str_contains(html_entity_decode($page), 'Less than 10 hours between shifts.'), 'the card has Approve and Decline inline and the warning as a chip');
ok(preg_match('/id="nav-approvals-count">(\d+)</', page($mara, '/')['body'], $m) && (int) $m[1] >= 1, 'the menu item carries a count badge (' . ($m[1] ?? '0') . ')');
ok(told($x) !== [] && in_array(33, told($x), true) && in_array(31, told($x), true), 'the outbox told the approvers (Mara) and the taker "sent to a manager"');
$p = page($lee, '/marketplace?tab=claims')['body'];
ok(str_contains($p, 'exchange-card-' . $x) && str_contains($p, 'Waiting for a manager'), 'Lee\'s My claims shows it: Waiting for a manager');
echo "   — Decline leaves the shift where it was and tells the taker\n";
$before = count(outbox($x));
[$c, $b] = act($mara, '/exchanges/decline.php', ['exchange' => $x, 'note' => 'SMOKE needs rest']);
ok($c === 200 && status_of($x) === 'declined' && holder_of($h) === 26, 'Decline: 200, the exchange is declined and the shift stays Priya\'s');
$news = array_slice(outbox($x), $before);
ok(in_array(31, array_map(fn ($r) => (int) $r['member_id'], $news), true) && $news[0]['kind'] === 'request_decided' && str_contains($news[0]['body'], 'declined'), 'the taker is told (request_decided, "declined")');
ok((int) one("SELECT count(*) FROM activity_log WHERE action = 'exchange.decline' AND entity_id = :x AND scope_id = 102", ['x' => $x]) === 1 && (int) one("SELECT count(*) FROM activity_log WHERE action = 'shift.assign' AND entity_id = :s", ['s' => $h]) === 0, 'exchange.decline is logged with the site; no shift.assign');
echo "   — Approve moves it\n";
$h2 = mkshift(102, srv(), 26, 520);
mkshift(102, srv(), 31, 512);                // 4 hours before → soft warning again
$x2 = offer($priya, $h2);
claim($lee, $x2);
$since = last_activity_id();
[$c, $b] = act($mara, '/exchanges/approve.php', ['exchange' => $x2, 'note' => 'SMOKE fine']);
ok($c === 200 && status_of($x2) === 'approved' && holder_of($h2) === 31, 'Approve: the shift moved to Lee');
ok((int) one("SELECT count(*) FROM activity_log WHERE action = 'exchange.approve' AND id > :s AND scope_id = 102", ['s' => $since]) === 1 && (int) one("SELECT count(*) FROM activity_log WHERE action = 'shift.assign' AND id > :s AND scope_id = 102", ['s' => $since]) === 1, 'one exchange.approve and one shift.assign, each with the site');
ok(in_array(26, told($x2), true) && in_array(31, told($x2), true), 'the holder and the taker are told');
[$c, $b] = act($mara, '/exchanges/approve.php', ['exchange' => $x2]);
ok($c === 422 && msg($b) === 'This trade is not waiting for a decision.', 'approving it again: 422 "This trade is not waiting for a decision."');
[$c, $b] = act($lee, '/exchanges/approve.php', ['exchange' => $x2]);
ok($c === 403 && msg($b) === 'You may not approve requests here.', 'a plain staff member may not approve: 403');

echo "2. approval_give = always / never\n";
$g1 = mkshift(102, srv(), 26, 600);
settings(102, ['approval_give' => 'always']);
[$c, $b] = act($priya, '/exchanges/give.php', ['shift' => $g1, 'colleague' => 31]);
$xg = (int) ($b['record_id'] ?? 0);
ok($c === 200 && status_of($xg) === 'pending_acceptance', 'Priya gives a shift to Lee: waiting for Lee');
ok(told($xg) === [31], 'the named colleague is told (only)');
[$c, $b] = act($lee, '/exchanges/accept.php', ['exchange' => $xg]);
ok($c === 200 && ($b['outcome'] ?? '') === 'pending_approval' && status_of($xg) === 'pending_approval' && holder_of($g1) === 26, 'always: Lee accepts and it waits for a manager; the shift has not moved');
[$c, $b] = act($mara, '/exchanges/approve.php', ['exchange' => $xg]);
ok($c === 200 && holder_of($g1) === 31, 'the manager approves: the shift is Lee\'s');
settings(102, ['approval_give' => 'never']);
$g2 = mkshift(102, srv(), 26, 640);
[$c, $b] = act($priya, '/exchanges/give.php', ['shift' => $g2, 'colleague' => 31]);
$xg2 = (int) $b['record_id'];
[$c, $b] = act($lee, '/exchanges/accept.php', ['exchange' => $xg2]);
ok($c === 200 && ($b['outcome'] ?? '') === 'approved' && holder_of($g2) === 31, 'never: Lee accepts and it goes through at once');
settings(102, ['approval_give' => 'on_warning']);

echo "3. A shift lead approves a same-day trade, and is refused a next-week one; staff are refused both\n";
settings(102, ['approval_pickup' => 'always']);
$sd = $W['sameday'];
$nw = $W['nextweek'];
$xs = offer($ana, $sd); $xn = offer($ana, $nw);
claim($lee, $xs); claim($lee, $xn);
ok(status_of($xs) === 'pending_approval' && status_of($xn) === 'pending_approval', 'with approval_pickup = always both claims wait for a manager');
[$c, $d] = screen($dana, '/approvals');
$ids = array_column($d['exchanges'] ?? [], 'exchange_id');
ok($c === 200 && in_array($xs, $ids, true) && !in_array($xn, $ids, true), 'Dana (shift lead) sees the same-day trade in her inbox and not the next-week one');
ok(in_array(32, told($xs), true) && !in_array(32, told($xn), true), 'and was told of the same-day one only');
[$c, $b] = act($dana, '/exchanges/approve.php', ['exchange' => $xn]);
ok($c === 403 && msg($b) === 'A shift lead approves trades for today or tomorrow only.', 'Dana approving the next-week trade: 403 "A shift lead approves trades for today or tomorrow only."');
[$c, $b] = act($priya, '/exchanges/approve.php', ['exchange' => $xs]);
ok($c === 403, 'a plain staff member approving the same-day trade: 403');
[$c, $b] = act($priya, '/exchanges/approve.php', ['exchange' => $xn]);
ok($c === 403, 'and the next-week one: 403');
[$c, $b] = act($priya, '/exchanges/decline.php', ['exchange' => $xs]);
ok($c === 403, 'nor may she decline: 403');
settings(102, ['shift_lead_approves_same_day' => false]);
[$c, $b] = act($dana, '/exchanges/approve.php', ['exchange' => $xs]);
ok($c === 403 && msg($b) === 'This restaurant does not let shift leads approve trades.', 'with the restaurant\'s setting off the lead is refused the same-day one too');
settings(102, ['shift_lead_approves_same_day' => true]);
[$c, $b] = act($dana, '/exchanges/approve.php', ['exchange' => $xs]);
ok($c === 200 && holder_of($sd) === 31 && status_of($xs) === 'approved', 'with it on, Dana approves the same-day trade: the shift is Lee\'s');
[$c, $b] = act($mara, '/exchanges/approve.php', ['exchange' => $xn]);
ok($c === 200 && holder_of($nw) === 31, 'Mara (manager) approves the next-week one');
echo "   — nobody decides a trade they are part of\n";
$d1 = mkshift(102, srv(), 30, 720);
$xd = offer($ana, $d1);
claim($dana, $xd);
ok(status_of($xd) === 'pending_approval', 'Dana claims a shift (always → a manager)');
[$c, $b] = act($dana, '/exchanges/approve.php', ['exchange' => $xd]);
ok($c === 403 && msg($b) === 'You cannot decide a trade you are part of.', 'Dana approving her own claim: 403 "You cannot decide a trade you are part of."');
[$c, $d] = screen($dana, '/approvals');
ok(!in_array($xd, array_column($d['exchanges'] ?? [], 'exchange_id'), true), 'and it is not in her own inbox');
$owner_r = act($owner, '/exchanges/approve.php', ['exchange' => $xd]);
ok($owner_r[0] === 200, 'the owner (admin at Airport) approves it');
settings(102, ['approval_pickup' => 'on_warning']);
[$c, $d] = screen($priya, '/approvals');
ok($c === 403, 'the Approvals screen for plain staff: 403');
finish();
