<?php
/** Proof — give and swap (spec "Proof", 6): the named colleague accepts or refuses; a swap checks both directions and says "The swap back: …". */
require __DIR__ . '/lib.php';
$W = world();
$priya = as_member(26); $ana = as_member(30); $lee = as_member(31); $marco = as_member(27, 101);

echo "1. Give\n";
$g = mkshift(102, srv(), 26, 800);
[$c, $b] = act($priya, '/exchanges/give.php', ['shift' => $g, 'colleague' => 27]);
ok($c === 422 && msg($b) === 'Pick a colleague here who works that position.', 'a colleague whose main restaurant is elsewhere (Marco) is not an eligible colleague: 422');
[$c, $b] = act($priya, '/exchanges/give.php', ['shift' => $g, 'colleague' => 26]);
ok($c === 422, 'nor herself');
$page = page($priya, '/shifts/' . $g)['body'];
ok(str_contains($page, 'id="give-form-field-colleague"') && str_contains($page, 'SMOKE Lee') && str_contains($page, 'SMOKE Ana') && !str_contains($page, 'SMOKE Marco') && !str_contains($page, 'SMOKE Joe'), 'the Give select lists colleagues here who hold the position — not Marco (main Downtown) or Joe (Downtown)');
[$c, $b] = act($priya, '/exchanges/give.php', ['shift' => $g, 'colleague' => 31, 'note' => 'SMOKE thanks']);
$x = (int) $b['record_id'];
ok($c === 200 && $b['location'] === "/exchanges/$x" && status_of($x) === 'pending_acceptance', 'Priya gives it to Lee: waiting for Lee (location ends in the exchange id)');
$row = q("SELECT scope_id, after FROM activity_log WHERE action = 'exchange.give' AND entity_id = :x", ['x' => $x])[0] ?? [];
ok((int) ($row['scope_id'] ?? 0) === 102 && str_contains((string) ($row['after'] ?? ''), '"to_member_id": 31'), 'exchange.give is logged with the site and the colleague');
ok(told($x) === [31], 'Lee is told (and only Lee)');
$page = page($lee, '/')['body'];
ok(str_contains($page, 'asked you to take a shift'), 'the dashboard\'s "Waiting for me" shows it to Lee');
$card = card_of($lee, $x, 'forme');
ok($card !== null && $card['may_take'] === true, 'Lee\'s "For me" tab has it, with Accept enabled');
$p = page($lee, '/marketplace?tab=forme')['body'];
ok(str_contains($p, 'id="exchange-card-' . $x . '-accept-btn"') && str_contains($p, 'id="exchange-card-' . $x . '-refuse-btn"'), 'with Accept and Refuse');
ok(card_of($ana, $x, 'forme') === null && page($ana, "/exchanges/$x")['code'] === 404, 'Ana cannot see it (404 by URL)');
[$c, $b] = act($ana, '/exchanges/accept.php', ['exchange' => $x]);
ok($c === 404, 'and cannot accept it: 404');
[$c, $b] = act($lee, '/exchanges/refuse.php', ['exchange' => $x]);
ok($c === 200 && status_of($x) === 'declined' && holder_of($g) === 26, 'Lee refuses: declined, the shift stays Priya\'s');
ok(in_array(26, told($x), true), 'Priya is told');
$g2 = mkshift(102, srv(), 26, 830);
[$c, $b] = act($priya, '/exchanges/give.php', ['shift' => $g2, 'colleague' => 31]);
$x2 = (int) $b['record_id'];
$since = last_activity_id();
[$c, $b] = act($lee, '/exchanges/accept.php', ['exchange' => $x2]);
ok($c === 200 && holder_of($g2) === 31 && status_of($x2) === 'approved', 'Lee accepts the other: the shift is his (no manager: approval_give on_warning, no warning)');
ok((int) one("SELECT count(*) FROM activity_log WHERE action = 'exchange.accept' AND id > :s AND scope_id = 102", ['s' => $since]) === 1 && (int) one("SELECT count(*) FROM activity_log WHERE action = 'shift.assign' AND id > :s AND scope_id = 102", ['s' => $since]) === 1, 'exchange.accept and shift.assign are each logged once, with the site');
[$c, $b] = act($lee, '/exchanges/accept.php', ['exchange' => $x2]);
ok($c === 422 && msg($b) === 'This trade is no longer waiting for you.', 'accepting twice: 422 "This trade is no longer waiting for you."');
[$c, $b] = act($priya, '/exchanges/cancel.php', ['exchange' => $x2]);
ok($c === 422 && msg($b) === 'This trade can no longer be withdrawn.', 'withdrawing a finished trade: 422');

echo "2. Swap — both directions\n";
$mine = mkshift(102, srv(), 26, 860);
$theirs = mkshift(102, srv(), 30, 880);
$bar = mkshift(102, $W['aBar'], 30, 900);
$page = page($priya, '/shifts/' . $mine . '?swap_with=30')['body'];
ok(str_contains($page, 'id="swap-form-field-swap_shift-' . $theirs . '"') && str_contains($page, 'id="swap-form-field-swap_shift-' . $bar . '"') && !str_contains($page, 'swap-form-field-swap_shift-' . $W['j1']), 'the Swap picker lists Ana\'s upcoming shifts here (and no Downtown shift)');
[$c, $b] = act($priya, '/exchanges/swap.php', ['shift' => $mine, 'colleague' => 30, 'swap_shift' => $W['j1']]);
ok($c === 422 && msg($b) === 'The shift to swap for is not that colleague\'s at this restaurant.', 'a swap for a shift that is not the colleague\'s: 422 "The shift to swap for is not that colleague\'s at this restaurant."');
[$c, $b] = act($priya, '/exchanges/swap.php', ['shift' => $mine, 'colleague' => 30, 'swap_shift' => $bar]);
$xs = (int) ($b['record_id'] ?? 0);
ok($c === 200 && status_of($xs) === 'pending_acceptance', 'Priya asks Ana to swap for Ana\'s Bar shift');
$card = card_of($ana, $xs, 'forme');
ok($card !== null && $card['kind'] === 'swap' && $card['may_take'] === true, 'Ana\'s "For me" tab shows the swap');
[$c, $b] = act($ana, '/exchanges/accept.php', ['exchange' => $xs]);
ok($c === 422 && msg($b) === 'The swap back: Does not work this position here.' && holder_of($mine) === 26 && holder_of($bar) === 30, 'Ana accepts and is refused "The swap back: Does not work this position here." (Priya does not work Bar); nothing moved');
[$c, $b] = act($priya, '/exchanges/cancel.php', ['exchange' => $xs]);
ok($c === 200 && status_of($xs) === 'cancelled', 'Priya withdraws it (the holder may)');
[$c, $b] = act($priya, '/exchanges/swap.php', ['shift' => $mine, 'colleague' => 30, 'swap_shift' => $theirs]);
$xs2 = (int) $b['record_id'];
$since = last_activity_id();
[$c, $b] = act($ana, '/exchanges/accept.php', ['exchange' => $xs2]);
ok($c === 200 && holder_of($mine) === 30 && holder_of($theirs) === 26 && status_of($xs2) === 'approved', 'the plain swap: Ana accepts and the two shifts trade hands');
ok((int) one("SELECT count(*) FROM activity_log WHERE action = 'shift.assign' AND id > :s AND scope_id = 102", ['s' => $since]) === 2, 'two shift.assign rows, one per shift');
$sw = q("SELECT entity_id, after FROM activity_log WHERE action = 'shift.assign' AND id > :s ORDER BY entity_id", ['s' => $since]);
ok(count($sw) === 2 && str_contains($sw[0]['after'] . $sw[1]['after'], 'SMOKE Ana') && str_contains($sw[0]['after'] . $sw[1]['after'], 'SMOKE Priya'), 'carrying who each went to');
$page = page($priya, '/exchanges/' . $xs2)['body'];
ok(str_contains($page, 'SMOKE Priya asked a colleague to swap it') && str_contains($page, 'id="exchange-swap"'), 'the trade page shows both shifts and Priya\'s part of the story');
finish();
