<?php
/** Proof — published means published (spec "Proof", 3): never deleted, changed and cancelled through their own actions, holders told and only them, a trade withdrawn. */
require __DIR__ . '/lib.php';
$W = w2(); reset_people();
$mara = as_member(33); $ana = as_member(30); $priya = as_member(26); $lee = as_member(31); $dana = as_member(32);
$srv = srv();
$ws = wk(35);
$A = fx(102, $srv, 30, $ws, 4, '17:00', '23:00'); $B = fx(102, $srv, 26, $ws, 5, '17:00', '23:00'); $C = fx(102, $srv, null, $ws, 5, '11:00', '15:00');
$wid = week_id_of(102, $ws);
[$c] = bp($mara, '/weeks/publish.php', ['week' => $wid]);
ok($c === 200, 'the week is published through the handler');

echo "1. Not deleted, not edited as a draft\n";
$n = (int) one('SELECT count(*) FROM shifts WHERE week_id = :w', ['w' => $wid]);
[$c, $b] = bp($mara, '/shifts/delete.php', ['shift' => $A]);
ok($c === 422 && msg($b) === 'A published shift is cancelled, never deleted.' && (int) one('SELECT count(*) FROM shifts WHERE week_id = :w', ['w' => $wid]) === $n, 'shift_delete on a published shift: 422 "' . msg($b) . '"');
ok(str_contains(admin_sql("DELETE FROM shifts WHERE id = $A"), 'never deleted'), 'and the database\'s own trigger refuses the same delete');
[$c, $b] = bp($mara, '/shifts/save.php', ['shift' => $A, 'note' => 'SMOKE x']);
ok($c === 422 && msg($b) === 'This week is published — use shift_change.', 'shift_update: 422 "' . msg($b) . '"');
[$c, $b] = bp($mara, '/shifts/assign.php', ['shift' => $A, 'assignee' => 31]);
ok($c === 422 && msg($b) === 'This week is published — use shift_change.', 'shift_assign: the same');
[$c, $b] = bp($mara, '/shifts/save.php', ['site' => 102, 'position' => $srv, 'date' => dayn($ws, 2), 'starts' => '17:00', 'ends' => '21:00']);
ok($c === 422 && msg($b) === 'This week is published — use shift_add.', 'shift_create into the published week: 422 "' . msg($b) . '"');

echo "2. shift_change\n";
$ob = last_outbox_id(); $since = last_activity_id();
[$c, $b] = bp($mara, '/shifts/change.php', ['shift' => $A, 'starts_at' => at($ws, 4, '17:00'), 'ends_at' => at($ws, 4, '22:00')]);
ok($c === 200 && $b['location'] === "/shifts/$A" && $b['notified'] === 1, 'shift_change: 200, one person told');
$row = q('SELECT ends_at, changed_after_publish_at, published_at FROM shifts WHERE id = :i', ['i' => $A])[0];
ok($row['changed_after_publish_at'] !== null && (new DateTimeImmutable($row['ends_at']))->setTimezone(new DateTimeZone(TZA))->format('H:i') === '22:00', 'it is stamped changed_after_publish_at (by the database) and the end moved');
$nt = shift_notices($A, $ob);
ok(array_values(array_unique(array_map(fn ($r) => (int) $r['member_id'], $nt))) === [30] && count($nt) === 2, 'one notice for the holder (Ana: email and text) and none for anyone else: ' . json_encode(array_column($nt, 'member_id')));
ok(str_contains($nt[0]['body'], 'Your shift changed') && str_contains($nt[0]['body'], 'Server') && !str_contains($nt[0]['body'], '21.37'), 'it says what changed, with the facts and no pay');
$lg = activity('shift.change', $since);
$after = json_decode((string) $lg[0]['after'], true); $before = json_decode((string) $lg[0]['before'], true);
ok(count($lg) === 1 && (int) $lg[0]['scope_id'] === 102 && $after['notified'] === [30] && isset($after['ends_at'], $before['ends_at']) && !isset($after['starts_at']), 'one shift.change row: the site, before/after only what changed, after.notified [30]');
[$c, $b] = bp($mara, '/shifts/change.php', ['shift' => $A, 'starts_at' => at($ws, 4, '17:00'), 'ends_at' => at($ws, 4, '22:00')]);
ok($c === 422 && msg($b) === 'Nothing changed.', 'a change that changes nothing: 422');
$d = jshifts($mara, 102, $ws);
ok($d[$A]['changed_after_publish'] === true && builder($mara, 102, $ws)[1]['state'] === 'changed', 'the builder says so: state changed');
$page = page($mara, "/builder?site=102&week=$ws")['body'];
ok(str_contains($page, 'Published — changed after') && str_contains($page, 'This week is live: staff will be told of every change.'), 'the page: "Published — changed after", and the live note');

echo "3. A reassignment tells both\n";
$ob = last_outbox_id();
[$c, $b] = bp($mara, '/shifts/change.php', ['shift' => $A, 'assignee' => 31]);
ok($c === 200 && $b['notified'] === 2, 'reassigning Ana\'s shift to Lee: 200, two people told');
$nt = shift_notices($A, $ob);
$by = []; foreach ($nt as $r) { $by[(int) $r['member_id']] = $r['body']; }
ok(array_keys($by) === [30, 31] || (isset($by[30], $by[31]) && count($by) === 2), 'notices to Ana and Lee, nobody else');
ok(str_contains($by[30], 'taken off your schedule') && str_contains($by[31], 'added to your schedule'), 'Ana: "taken off your schedule"; Lee: "added to your schedule"');
ok((int) one('SELECT assignee_member_id FROM shifts WHERE id = :i', ['i' => $A]) === 31, 'and the shift is Lee\'s');
[$c, $b] = bp($mara, '/shifts/change.php', ['shift' => $A, 'assignee' => 26, 'starts_at' => at($ws, 4, '17:00'), 'ends_at' => at($ws, 4, '22:00')]);
ok($c === 200, 'back to a person with no clash (Priya)');
[$c, $b] = bp($mara, '/shifts/change.php', ['shift' => $A, 'assignee' => 30]);
ok($c === 200, 'and to Ana');
[$c, $b] = bp($mara, '/shifts/change.php', ['shift' => $A, 'assignee' => 26, 'starts_at' => at($ws, 5, '18:00'), 'ends_at' => at($ws, 5, '21:00')]);
ok($c === 422 && str_contains(msg($b), 'SMOKE Priya already has a shift then'), 'moving it onto Priya\'s Saturday shift is refused: "' . msg($b) . '"');

echo "4. shift_cancel — the trade goes, the holder is told, the row stays\n";
$x = offer($priya, $B);
ok($x > 0 && status_of($x) === 'open', 'Priya offers her Saturday shift: a live trade');
$ob = last_outbox_id(); $since = last_activity_id();
[$c, $b] = bp($mara, '/shifts/cancel.php', ['shift' => $B]);
ok($c === 422 && str_contains(msg($b), 'Give a reason'), 'no reason: 422 "' . msg($b) . '"');
[$c, $b] = bp($mara, '/shifts/cancel.php', ['shift' => $B, 'reason' => 'SMOKE the walk-in broke']);
ok($c === 200 && $b['exchange_cancelled'] === 1 && $b['notified'] === 1, 'shift_cancel with a reason: 200, one trade withdrawn, one person told');
$row = q('SELECT status, cancelled_at, cancel_reason FROM shifts WHERE id = :i', ['i' => $B])[0];
ok($row['status'] === 'cancelled' && $row['cancelled_at'] !== null && $row['cancel_reason'] === 'SMOKE the walk-in broke', 'the shift is cancelled and KEPT, with the reason');
ok(status_of($x) === 'cancelled', 'its live trade is cancelled');
$nt = shift_notices($B, $ob);
ok(count($nt) === 2 && (int) $nt[0]['member_id'] === 26 && str_contains($nt[0]['body'], 'was cancelled') && str_contains($nt[0]['body'], 'the walk-in broke'), 'Priya is told, with the reason');
$lg = activity('shift.cancel', $since); $after = json_decode((string) $lg[0]['after'], true);
ok(count($lg) === 1 && $after['reason'] === 'SMOKE the walk-in broke' && $after['exchange_cancelled'] === 1 && $after['notified'] === [26], 'one shift.cancel row: reason, exchange_cancelled 1, notified [26]');
ok(count(activity('exchange.cancel', $since)) === 1, 'and one exchange.cancel row for the withdrawn trade');
[$c, $b] = bp($mara, '/shifts/cancel.php', ['shift' => $B, 'reason' => 'SMOKE again']);
ok($c === 422 && msg($b) === 'That shift is already cancelled.', 'cancelling again: 422');
$page = page($mara, "/shifts/$B")['body'];
ok(str_contains($page, 'Cancelled') && str_contains($page, 'never deleted'), 'the shift page shows it cancelled');
$d = jshifts($mara, 102, $ws);
ok($d[$B]['status'] === 'cancelled', 'the builder still shows it (struck through)');
$page = page($mara, "/builder?site=102&week=$ws")['body'];
ok(str_contains($page, 'shift-cancelled'), 'with the cancelled class');
$mine = jshifts($priya, 102, $ws);
[, $dd] = screen($priya, "/my-schedule?week=$ws");
ok(!in_array($B, array_column($dd['shifts'] ?? [], 'shift_id'), true), 'and Priya\'s schedule no longer lists it');

echo "5. shift_add\n";
$ob = last_outbox_id(); $since = last_activity_id();
[$c, $b] = bp($mara, '/shifts/add.php', ['site' => 102, 'position' => $srv, 'date' => dayn($ws, 6), 'starts' => '12:00', 'ends' => '16:00', 'assignee' => 31]);
$new = (int) ($b['record_id'] ?? 0);
ok($c === 200 && $b['location'] === "/shifts/$new" && $b['notified'] === 1, 'shift_add: 200, the location ends in the new shift\'s id, one person told');
$row = q('SELECT published_at, changed_after_publish_at FROM shifts WHERE id = :i', ['i' => $new])[0];
ok($row['published_at'] !== null && $row['changed_after_publish_at'] !== null, 'live at once: published_at and changed_after_publish_at set by the database');
$nt = shift_notices($new, $ob);
ok(count($nt) === 2 && (int) $nt[0]['member_id'] === 31, 'only Lee is told');
ok(count(activity('shift.add', $since)) === 1 && (int) activity('shift.add', $since)[0]['scope_id'] === 102, 'one shift.add row with the site');
[$c, $b] = bp($mara, '/shifts/add.php', ['site' => 102, 'position' => $srv, 'date' => dayn(wk(48), 2), 'starts' => '12:00', 'ends' => '16:00']);
ok($c === 422 && msg($b) === 'That week is not published yet — use shift_create.', 'shift_add into a week that is not published: 422 "' . msg($b) . '"');
[, $open] = [0, jshifts($mara, 102, $ws)];
ok(isset($open[$C]), 'the open shift is still there for the team');
[$c, $b] = bp($mara, '/shifts/add.php', ['site' => 102, 'position' => $srv, 'date' => dayn($ws, 6), 'starts' => '13:00', 'ends' => '17:00', 'assignee' => 31]);
ok($c === 422 && str_contains(msg($b), 'SMOKE Lee already has a shift then'), 'a clash on a live week is refused as in a draft: "' . msg($b) . '"');

echo "6. Live forms say so\n";
$r = page($mara, '/shifts/new?site=102&date=' . dayn($ws, 3));
ok($r['code'] === 200 && str_contains($r['body'], 'This is live: staff will be told.') && str_contains($r['body'], 'action="/shifts/add.php"') && str_contains($r['body'], 'Add it and tell staff'), 'the add form for a published week posts shift_add and says "This is live: staff will be told."');
$r = page($mara, "/shifts/$A/edit");
ok($r['code'] === 200 && str_contains($r['body'], 'action="/shifts/change.php"') && str_contains($r['body'], 'hx-confirm="This is live'), 'the edit form posts shift_change, with a confirm');
$r = page($mara, "/shifts/$A");
ok(str_contains($r['body'], 'id="shift-cancel-form"') && str_contains($r['body'], 'This is live: staff will be told. Cancel this shift?') && str_contains($r['body'], 'id="shift-move-' . $A . '-form"'), 'the shift page: Cancel shift with its confirm, and Move to…');
$r = page($priya, "/shifts/$A");
ok(!str_contains($r['body'], 'shift-cancel-form') && !str_contains($r['body'], 'shift-edit-link'), 'and none of it for a person who does not build');
[$c, $b] = bp($priya, '/shifts/change.php', ['shift' => $A, 'note' => 'x']);
ok($c === 403, 'a POST of shift_change by Priya: 403');
finish();
