<?php
/** Proof — templates and copying (spec "Proof", 5): save a week, apply it to a draft (weekdays, the person on leave left open and listed, a published week refused), copy last week (across a clock change), clear. */
require __DIR__ . '/lib.php';
$W = w2(); reset_people();
$mara = as_member(33); $priya = as_member(26); $marco = as_member(27, 101); $dee = as_dee();
$srv = srv();
$T = wk(37); $U = wk(38);
fx(102, $srv, 30, $T, 0); fx(102, $srv, 26, $T, 2); fx(102, $srv, null, $T, 4, '11:00', '15:00'); fx(102, $srv, 31, $T, 5, '22:00', '02:00', ['break' => 0]);
$tw = week_id_of(102, $T);

echo "1. Save a week as a template\n";
[$c, $b] = bp($mara, '/templates/save.php', ['site' => 102, 'week' => $tw]);
ok($c === 422 && str_contains(msg($b), 'name'), 'no name: 422 "' . msg($b) . '"');
$since = last_activity_id();
[$c, $b] = bp($mara, '/templates/save.php', ['site' => 102, 'name' => 'SMOKE Standard', 'week' => $tw]);
$tid = (int) ($b['record_id'] ?? 0);
ok($c === 200 && $b['location'] === "/templates/$tid" && $b['shift_count'] === 4, 'template_save: 200, the location ends in the template\'s id, 4 shifts');
$rows = q('SELECT weekday, starts_at::text AS s, ends_at::text AS e, assignee_member_id FROM template_shifts WHERE template_id = :t ORDER BY weekday', ['t' => $tid]);
ok(array_map(fn ($r) => [(int) $r['weekday'], substr($r['s'], 0, 5), substr($r['e'], 0, 5)], $rows) === [[1, '17:00', '23:00'], [3, '17:00', '23:00'], [5, '11:00', '15:00'], [6, '22:00', '02:00']], 'weekday (0 = Sunday), local times, and the overnight one kept as 22:00–02:00: ' . json_encode(array_map(fn ($r) => [$r['weekday'], $r['s'], $r['e']], $rows)));
ok((int) $rows[0]['assignee_member_id'] === 30 && $rows[2]['assignee_member_id'] === null, 'the person is kept when chosen; an open shift stays open');
ok(count(activity('template.save', $since)) === 1 && (int) activity('template.save', $since)[0]['scope_id'] === 102, 'one template.save row with the site');
[, $l] = screen($mara, '/templates/?site=102');
ok(in_array($tid, array_column($l['templates'], 'template_id'), true), 'it is in the list');
$r = page($mara, "/templates/$tid");
ok($r['code'] === 200 && str_contains($r['body'], 'data-screen="template-view"') && str_contains($r['body'], 'Start a week from it') && str_contains($r['body'], 'Saturday') && str_contains($r['body'], '10:00 pm–2:00 am'), 'the template page: by weekday, "Start a week from it"');
[$c, $b] = bp($mara, '/templates/save.php', ['site' => 102, 'template' => $tid, 'name' => 'SMOKE Standard week']);
ok($c === 200 && (string) one('SELECT name FROM schedule_templates WHERE id = :i', ['i' => $tid]) === 'SMOKE Standard week' && (int) one('SELECT count(*) FROM template_shifts WHERE template_id = :t', ['t' => $tid]) === 4, 'renaming keeps its shifts');

echo "2. Apply it to a draft week — the person on time off is left open and listed\n";
time_off(30, dayn($U, 0));
$since = last_activity_id();
[$c, $b] = bp($mara, '/templates/apply.php', ['template' => $tid, 'site' => 102, 'week_start' => dayn($U, 3)]);
ok($c === 200 && $b['placed'] === 4 && count($b['left_open']) === 1 && $b['existing'] === 0, 'template_apply: 4 placed, 1 left open');
ok(str_contains($b['left_open'][0]['reason'], 'SMOKE Ana has time off Monday.'), 'the reason: "' . $b['left_open'][0]['reason'] . '"');
$uw = week_id_of(102, $U);
$got = q('SELECT starts_at, ends_at, assignee_member_id FROM shifts WHERE week_id = :w ORDER BY starts_at', ['w' => $uw]);
ok(array_map(fn ($r) => loc($r['starts_at']), $got) === [dayn($U, 0) . ' 17:00', dayn($U, 2) . ' 17:00', dayn($U, 4) . ' 11:00', dayn($U, 5) . ' 22:00'], 'every shift landed on its weekday of the target week (Monday, Wednesday, Friday, Saturday)');
ok(loc($got[3]['ends_at']) === dayn($U, 6) . ' 02:00', 'the overnight shift ends Sunday 02:00');
ok($got[0]['assignee_member_id'] === null && (int) $got[1]['assignee_member_id'] === 26 && (int) $got[3]['assignee_member_id'] === 31, 'Ana\'s shift is open; Priya and Lee kept theirs');
ok(count(activity('template.apply', $since)) === 1, 'one template.apply row');
$after = json_decode((string) activity('template.apply', $since)[0]['after'], true);
ok($after['placed'] === 4 && $after['left_open'] === 1 && $after['week_id'] === $uw, 'template.apply: placed 4, left_open 1, the week');
$page = page($mara, "/builder?site=102&week=$U")['body'];
ok(str_contains($page, 'id="builder-result"') && str_contains($page, 'SMOKE Ana has time off Monday.') && str_contains($page, '1 left open'), 'the builder lists it once, in the result card: "…3 placed, 1 left open"');
$page2 = page($mara, "/builder?site=102&week=$U")['body'];
ok(!str_contains($page2, 'id="builder-result"'), 'and only once');
[$c, $b] = bp($mara, '/templates/apply.php', ['template' => $tid, 'site' => 102, 'week_start' => $U]);
ok($c === 200 && $b['existing'] === 4 && $b['placed'] === 4, 'applying again adds beside the four already there (and reports them): existing 4');
ok(count(array_filter($b['left_open'], fn ($x) => str_contains($x['reason'], 'already has a shift'))) === 2 && count($b['left_open']) === 3, 'Priya and Lee would now clash with themselves: left open ("already has a shift"), Ana still on leave: ' . count($b['left_open']));
[$c, $b] = bp($mara, '/weeks/clear.php', ['week' => $uw]);
ok($c === 200 && $b['removed'] === 8 && (int) one('SELECT count(*) FROM shifts WHERE week_id = :w', ['w' => $uw]) === 0, 'week_clear: the eight draft shifts are removed');

echo "3. A published week is never filled\n";
$P = wk(39);
fx(102, $srv, 26, $P, 1);
[$c] = bp($mara, '/weeks/publish.php', ['week' => week_id_of(102, $P)]);
ok($c === 200, 'a week is published');
$before = (int) one('SELECT count(*) FROM shifts WHERE week_id = :w', ['w' => week_id_of(102, $P)]);
[$c, $b] = bp($mara, '/templates/apply.php', ['template' => $tid, 'site' => 102, 'week_start' => $P]);
ok($c === 422 && msg($b) === 'This week is published.', 'template_apply onto it: 422 "' . msg($b) . '"');
[$c, $b] = bp($mara, '/weeks/copy.php', ['site' => 102, 'week_start' => $P, 'from_week' => $tw]);
ok($c === 422 && msg($b) === 'This week is published.', 'week_copy onto it: 422');
[$c, $b] = bp($mara, '/weeks/clear.php', ['week' => week_id_of(102, $P)]);
ok($c === 422 && msg($b) === 'This week is published.', 'week_clear of it: 422');
[$c, $b] = bp($mara, '/weeks/autofill.php', ['week' => week_id_of(102, $P)]);
ok($c === 422 && msg($b) === 'This week is published.', 'week_autofill of it: 422');
ok((int) one('SELECT count(*) FROM shifts WHERE week_id = :w', ['w' => week_id_of(102, $P)]) === $before, 'and nothing was added');

echo "4. Copy last week\n";
$V = wk(40);
$since = last_activity_id();
[$c, $b] = bp($mara, '/weeks/copy.php', ['site' => 102, 'week_start' => $V, 'from_week' => $tw]);
ok($c === 200 && $b['placed'] === 4 && $b['left_open'] === [], 'week_copy: 4 placed, none left open');
$got = q('SELECT starts_at, assignee_member_id FROM shifts WHERE week_id = :w ORDER BY starts_at', ['w' => week_id_of(102, $V)]);
ok(array_map(fn ($r) => loc($r['starts_at']), $got) === [dayn($V, 0) . ' 17:00', dayn($V, 2) . ' 17:00', dayn($V, 4) . ' 11:00', dayn($V, 5) . ' 22:00'] && (int) $got[0]['assignee_member_id'] === 30, 'same weekdays and times, the people kept');
$log = activity('week.copy', $since); $after = json_decode((string) $log[0]['after'], true);
ok(count($log) === 1 && $after['from_week'] === $tw && $after['placed'] === 4 && $after['left_open'] === 0, 'week.copy: from_week, placed, left_open');
$A22 = wk(22); $A26 = wk(26);
fx(102, $srv, 30, $A22, 3, '17:00', '23:00');
[$c, $b] = bp($mara, '/weeks/copy.php', ['site' => 102, 'week_start' => $A26, 'from_week' => week_id_of(102, $A22)]);
$row = q('SELECT starts_at FROM shifts WHERE week_id = :w', ['w' => week_id_of(102, $A26)])[0];
$orig = q('SELECT starts_at FROM shifts WHERE week_id = :w', ['w' => week_id_of(102, $A22)])[0];
ok($c === 200 && loc($row['starts_at']) === dayn($A26, 3) . ' 17:00' && (new DateTimeImmutable($row['starts_at']))->format('H') !== (new DateTimeImmutable($orig['starts_at']))->format('H'), 'across the clock change (CST → CDT) the LOCAL time stays 17:00 (the UTC hour moved from ' . (new DateTimeImmutable($orig['starts_at']))->format('H') . ' to ' . (new DateTimeImmutable($row['starts_at']))->format('H') . ')');
[$c, $b] = bp($mara, '/weeks/copy.php', ['site' => 102, 'week_start' => $V, 'from_week' => $tw]);
ok($c === 200 && $b['existing'] === 4 && count($b['left_open']) === 3, 'copying into a week that has shifts adds beside them (existing 4) and the clashes are left open');
[$c, $b] = bp($mara, '/weeks/copy.php', ['week' => week_id_of(102, $V), 'from_week' => week_id_of(102, $V)]);
ok($c === 422 && msg($b) === 'Pick a different week to copy from.', 'copying a week onto itself: 422');
[$c, $b] = bp($mara, '/weeks/copy.php', ['site' => 102, 'week_start' => wk(41)]);
ok($c === 422 && str_contains(msg($b), 'from_week'), 'no from_week: 422');
$dw = fx(101, (int) $W['dSrv'], 34, wk(37), 1);
[$c, $b] = bp($mara, '/weeks/copy.php', ['site' => 102, 'week_start' => wk(41), 'from_week' => week_id_of(101, wk(37))]);
ok($c === 404 && msg($b) === 'Week not found.', 'a week of another restaurant (Downtown) cannot be copied from: 404 "Week not found."');

echo "5. Other restaurants and other rights\n";
[$c, $l] = screen($dee, '/templates/?site=101');
ok($c === 200 && !in_array($tid, array_column($l['templates'] ?? [], 'template_id'), true), 'a Downtown manager\'s template list does not show Airport\'s');
$r = page($dee, '/templates/?site=102');
ok($r['code'] === 404, 'Dee opening Airport\'s templates: 404');
$r = page($dee, "/templates/$tid");
ok($r['code'] === 404 && str_contains($r['body'], 'That template is not here any more.'), 'Dee opening the Airport template by URL: 404 "That template is not here any more."');
[$c, $b] = bp($dee, '/templates/apply.php', ['template' => $tid, 'site' => 101, 'week_start' => wk(41)]);
ok($c === 404 && msg($b) === 'That template is not here any more.', 'Dee applying it: 404');
[$c, $b] = bp($marco, '/templates/apply.php', ['template' => $tid, 'site' => 102, 'week_start' => wk(41)]);
ok($c === 403, 'Marco (manager at Downtown, only staff at Airport) applying it: 403');

echo "6. Archive\n";
$since = last_activity_id();
[$c, $b] = bp($mara, '/templates/archive.php', ['template' => $tid]);
ok($c === 200 && count(activity('template.archive', $since)) === 1, 'template_archive: 200, one template.archive row');
[, $l] = screen($mara, '/templates/?site=102');
ok(!in_array($tid, array_column($l['templates'], 'template_id'), true), 'it leaves the list');
[$c, $b] = bp($mara, '/templates/apply.php', ['template' => $tid, 'site' => 102, 'week_start' => wk(41)]);
ok($c === 422 && msg($b) === 'That template is archived.', 'applying it: 422 "' . msg($b) . '"');
ok((int) one('SELECT count(*) FROM template_shifts WHERE template_id = :t', ['t' => $tid]) === 4, 'and it is kept, not deleted');
finish();
